/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controler.Conectar;
import static View.GUICadUsuario.pegarfunc;
import static View.GUIPesquisarClientes.pesqclidtnasc;
import static View.GUIPesquisarFuncionario.alteracaofuncionario;
import static View.GUIPesquisarFuncionario.codigofuncionario;
import static View.GUIPesquisarFuncionario.pesqfuncbairro;
import static View.GUIPesquisarFuncionario.pesqfunccep;
import static View.GUIPesquisarFuncionario.pesqfunccomi;
import static View.GUIPesquisarFuncionario.pesqfunccompl;
import static View.GUIPesquisarFuncionario.pesqfunccpf;
import static View.GUIPesquisarFuncionario.pesqfuncctps;
import static View.GUIPesquisarFuncionario.pesqfuncdtnasc;
import static View.GUIPesquisarFuncionario.pesqfuncemail;
import static View.GUIPesquisarFuncionario.pesqfuncend;
import static View.GUIPesquisarFuncionario.pesqfuncnome;
import static View.GUIPesquisarFuncionario.pesqfuncperi;
import static View.GUIPesquisarFuncionario.pesqfuncrg;
import static View.GUIPesquisarFuncionario.pesqfuncsal;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

public class GUICadfuncionario extends javax.swing.JFrame {

    static long cpf;
    static long rg;
    static long ctps;
    static String nome;
    static String dtnasc;
    static String end;
    static int endn;
    static String bairro;
    static String compl;
    static long cep;
    static long tel;
    static float sal;
    static float comi;
    static String peri;
    static String email;
    static int cod;
    String url2 = "jdbc:mysql://localhost/loja"; // enderço do BD
  String username = "root";        //nome de um usuário de seu BD
  String password = "";  // senha do BD
    
    public GUICadfuncionario() {
     Model.LookAndFeel.estilo();         initComponents();
              this.setDefaultCloseOperation(2);      this.setResizable(false);   this.setTitle("FaciModas 1.0"); 
              
              
              DecimalFormat dFormat = new DecimalFormat("#,###,###.00") ;
        NumberFormatter formatter = new NumberFormatter(dFormat) ;
        formatter.setFormat(dFormat) ;
        formatter.setAllowsInvalid(false) ;      
        txtcomfunc.setFormatterFactory ( new DefaultFormatterFactory ( formatter ) ) ;
        txtsalariofunc.setFormatterFactory ( new DefaultFormatterFactory ( formatter ) ) ;
             
         if (alteracaofuncionario == true ){

DateFormat formate = new SimpleDateFormat("yyyy-dd-MM");
                    Date dtconvert=null;
            try {
   dtconvert = (java.util.Date) formate.parse(pesqfuncdtnasc);
               
                
            } catch (ParseException ex) {
                Logger.getLogger(GUICadfuncionario.class.getName()).log(Level.SEVERE, null, ex);
            }
           

 cod = codigofuncionario;
        txtcpffunc.setText(pesqfunccpf);
                txtrgfunc.setText(pesqfuncrg);
                txtctpsfunc.setText(pesqfuncctps);
                txtnomefunc.setText(pesqfuncnome);
                datanascfunc.setDate(dtconvert);
                txtendfunc.setText(pesqfuncend);
                txtbairrofunc.setText(pesqfuncbairro);
                txtcompfunc.setText(pesqfunccompl);
                txtemaifunc.setText(pesqfuncemail);
                txtsalariofunc.setText(pesqfuncsal);
                txtcomfunc.setText(pesqfunccomi);
                comboboxperfunc.setSelectedItem(pesqfuncperi);
                txtcepfunc.setText(pesqfunccep);
        lblselecionar.setText("Alterar Funcionário");
       bttcadastrarfuncionario.setText("Salvar");
 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelimgpro = new javax.swing.JLabel();
        labelnomefunc = new javax.swing.JLabel();
        txtnomefunc = new javax.swing.JTextField();
        labelcpffunc = new javax.swing.JLabel();
        labelrgfunc = new javax.swing.JLabel();
        labeldtnasfunc = new javax.swing.JLabel();
        datanascfunc = new com.toedter.calendar.JDateChooser();
        labelendfunc = new javax.swing.JLabel();
        txtendfunc = new javax.swing.JTextField();
        labelbairrofunc = new javax.swing.JLabel();
        txtbairrofunc = new javax.swing.JTextField();
        labelcomplfunc = new javax.swing.JLabel();
        txtcompfunc = new javax.swing.JTextField();
        labelcepfunc = new javax.swing.JLabel();
        labeltelfunc = new javax.swing.JLabel();
        labelemailfunc = new javax.swing.JLabel();
        txtemaifunc = new javax.swing.JTextField();
        txtctpsfunc = new javax.swing.JTextField();
        labelcpfcliente1 = new javax.swing.JLabel();
        labelsalariofunc = new javax.swing.JLabel();
        labelperfunc = new javax.swing.JLabel();
        comboboxperfunc = new javax.swing.JComboBox();
        labelcomifunc = new javax.swing.JLabel();
        bttcadastrarfuncionario = new javax.swing.JButton();
        bttlimparfuncionario = new javax.swing.JButton();
        bttvoltarmenupesquisar = new javax.swing.JButton();
        lblselecionar = new javax.swing.JLabel();
        txtcpffunc = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter cpf= new 

            javax.swing.text.MaskFormatter("###.###.###-##");

            txtcpffunc = new javax.swing.JFormattedTextField(cpf);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txtrgfunc = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter rg= new 

            javax.swing.text.MaskFormatter("##.###.###-#");

            txtrgfunc = new javax.swing.JFormattedTextField(rg);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txtcepfunc = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter cep= new 

            javax.swing.text.MaskFormatter("#####-###");

            txtcepfunc = new javax.swing.JFormattedTextField(cep);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txttelfunc = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter tel= new 

            javax.swing.text.MaskFormatter("(##) ####-####");

            txttelfunc = new javax.swing.JFormattedTextField(tel);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txtsalariofunc = new javax.swing.JFormattedTextField();
        txtcomfunc = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        labelimgpro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranco1.png"))); // NOI18N
        labelimgpro.setText("jLabel1");
        jPanel1.add(labelimgpro);
        labelimgpro.setBounds(-20, -10, 200, 110);

        labelnomefunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelnomefunc.setForeground(new java.awt.Color(255, 255, 255));
        labelnomefunc.setText("Nome:");
        jPanel1.add(labelnomefunc);
        labelnomefunc.setBounds(30, 130, 60, 30);
        jPanel1.add(txtnomefunc);
        txtnomefunc.setBounds(90, 130, 540, 30);

        labelcpffunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcpffunc.setForeground(new java.awt.Color(255, 255, 255));
        labelcpffunc.setText("CPF:");
        jPanel1.add(labelcpffunc);
        labelcpffunc.setBounds(30, 170, 50, 30);

        labelrgfunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelrgfunc.setForeground(new java.awt.Color(255, 255, 255));
        labelrgfunc.setText("RG:");
        jPanel1.add(labelrgfunc);
        labelrgfunc.setBounds(350, 170, 40, 30);

        labeldtnasfunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labeldtnasfunc.setForeground(new java.awt.Color(255, 255, 255));
        labeldtnasfunc.setText("Data de nascimento:");
        jPanel1.add(labeldtnasfunc);
        labeldtnasfunc.setBounds(640, 130, 120, 30);
        jPanel1.add(datanascfunc);
        datanascfunc.setBounds(760, 130, 120, 30);

        labelendfunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelendfunc.setForeground(new java.awt.Color(255, 255, 255));
        labelendfunc.setText("Endereço: ");
        jPanel1.add(labelendfunc);
        labelendfunc.setBounds(30, 210, 60, 30);
        jPanel1.add(txtendfunc);
        txtendfunc.setBounds(90, 210, 540, 30);

        labelbairrofunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelbairrofunc.setForeground(new java.awt.Color(255, 255, 255));
        labelbairrofunc.setText("Bairro:");
        jPanel1.add(labelbairrofunc);
        labelbairrofunc.setBounds(640, 210, 60, 30);
        jPanel1.add(txtbairrofunc);
        txtbairrofunc.setBounds(690, 210, 190, 30);

        labelcomplfunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcomplfunc.setForeground(new java.awt.Color(255, 255, 255));
        labelcomplfunc.setText("Complemento:");
        jPanel1.add(labelcomplfunc);
        labelcomplfunc.setBounds(290, 250, 100, 30);
        jPanel1.add(txtcompfunc);
        txtcompfunc.setBounds(370, 250, 260, 30);

        labelcepfunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcepfunc.setForeground(new java.awt.Color(255, 255, 255));
        labelcepfunc.setText("CEP:");
        jPanel1.add(labelcepfunc);
        labelcepfunc.setBounds(30, 250, 60, 30);

        labeltelfunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labeltelfunc.setForeground(new java.awt.Color(255, 255, 255));
        labeltelfunc.setText("Telefone:");
        jPanel1.add(labeltelfunc);
        labeltelfunc.setBounds(30, 290, 60, 30);

        labelemailfunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelemailfunc.setForeground(new java.awt.Color(255, 255, 255));
        labelemailfunc.setText("Email:");
        jPanel1.add(labelemailfunc);
        labelemailfunc.setBounds(290, 290, 60, 30);
        jPanel1.add(txtemaifunc);
        txtemaifunc.setBounds(370, 290, 260, 30);
        jPanel1.add(txtctpsfunc);
        txtctpsfunc.setBounds(690, 170, 190, 30);

        labelcpfcliente1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcpfcliente1.setForeground(new java.awt.Color(255, 255, 255));
        labelcpfcliente1.setText("CTPS:");
        jPanel1.add(labelcpfcliente1);
        labelcpfcliente1.setBounds(640, 170, 50, 30);

        labelsalariofunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelsalariofunc.setForeground(new java.awt.Color(255, 255, 255));
        labelsalariofunc.setText("Salário:");
        jPanel1.add(labelsalariofunc);
        labelsalariofunc.setBounds(30, 370, 70, 30);

        labelperfunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelperfunc.setForeground(new java.awt.Color(255, 255, 255));
        labelperfunc.setText("Período :");
        jPanel1.add(labelperfunc);
        labelperfunc.setBounds(30, 330, 60, 30);

        comboboxperfunc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manhã", "Tarde", "Noite" }));
        jPanel1.add(comboboxperfunc);
        comboboxperfunc.setBounds(90, 330, 130, 30);

        labelcomifunc.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcomifunc.setForeground(new java.awt.Color(255, 255, 255));
        labelcomifunc.setText("Comissão:");
        jPanel1.add(labelcomifunc);
        labelcomifunc.setBounds(30, 410, 60, 30);

        bttcadastrarfuncionario.setBackground(new java.awt.Color(0, 0, 0));
        bttcadastrarfuncionario.setForeground(new java.awt.Color(255, 255, 255));
        bttcadastrarfuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconsave.png"))); // NOI18N
        bttcadastrarfuncionario.setText("Cadastrar");
        bttcadastrarfuncionario.setBorder(null);
        bttcadastrarfuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttcadastrarfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcadastrarfuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(bttcadastrarfuncionario);
        bttcadastrarfuncionario.setBounds(490, 470, 140, 30);

        bttlimparfuncionario.setBackground(new java.awt.Color(0, 0, 0));
        bttlimparfuncionario.setForeground(new java.awt.Color(255, 255, 255));
        bttlimparfuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconlimpar.png"))); // NOI18N
        bttlimparfuncionario.setText("Limpar");
        bttlimparfuncionario.setBorder(null);
        bttlimparfuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttlimparfuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttlimparfuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(bttlimparfuncionario);
        bttlimparfuncionario.setBounds(340, 470, 140, 30);

        bttvoltarmenupesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltaresquerdanovo.jpg"))); // NOI18N
        bttvoltarmenupesquisar.setToolTipText("Voltar para o menu de pesquisas!");
        bttvoltarmenupesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bttvoltarmenupesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttvoltarmenupesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttvoltarmenupesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(bttvoltarmenupesquisar);
        bttvoltarmenupesquisar.setBounds(40, 500, 40, 40);

        lblselecionar.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblselecionar.setForeground(new java.awt.Color(255, 255, 255));
        lblselecionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblselecionar.setText("Cadastrar Funcionário");
        lblselecionar.setToolTipText("");
        jPanel1.add(lblselecionar);
        lblselecionar.setBounds(80, 50, 800, 40);
        jPanel1.add(txtcpffunc);
        txtcpffunc.setBounds(90, 170, 230, 30);
        jPanel1.add(txtrgfunc);
        txtrgfunc.setBounds(380, 170, 250, 30);
        jPanel1.add(txtcepfunc);
        txtcepfunc.setBounds(90, 250, 130, 30);
        jPanel1.add(txttelfunc);
        txttelfunc.setBounds(90, 290, 130, 30);
        jPanel1.add(txtsalariofunc);
        txtsalariofunc.setBounds(90, 370, 130, 30);
        jPanel1.add(txtcomfunc);
        txtcomfunc.setBounds(90, 410, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 580);

        setSize(new java.awt.Dimension(931, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttvoltarmenupesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttvoltarmenupesquisarActionPerformed
            if (pegarfunc == true){
                pegarfunc = false;
    new GUIPesquisarFuncionario().setVisible(true);
    this.dispose();    
}else{
               if(alteracaofuncionario == true){
                   alteracaofuncionario = false;
        new GUIPesquisarFuncionario().setVisible(true);      this.dispose();    
}else{
                new GUICadastrarMenu().setVisible(true);
         this.dispose();
            }
            }
    }//GEN-LAST:event_bttvoltarmenupesquisarActionPerformed

    private void bttcadastrarfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcadastrarfuncionarioActionPerformed
 String tr = txtcpffunc.getText();
        tr = tr.replace(".", "");
        tr = tr.replace("-", "");              
                cpf = Long.valueOf(tr);
                 tr = txtrgfunc.getText();
        tr = tr.replace(".", "");
        tr = tr.replace("-", "");       
                rg = Long.valueOf(tr);
                ctps = Long.valueOf(txtctpsfunc.getText());
                nome = txtnomefunc.getText();
                dtnasc = new SimpleDateFormat("yyyy-MM-dd").format(datanascfunc.getDate());
                end = txtendfunc.getText();
                bairro = txtbairrofunc.getText();
                compl = txtcompfunc.getText();
                 tr = txtcepfunc.getText();
   
        tr = tr.replace("-", "");       
                cep = Long.valueOf(tr);
                 tr = txttelfunc.getText();
         tr = tr.replace("-", "");
         tr = tr.replace("(", "");
         tr = tr.replace(")", "");
           tr = tr.replace(" ", "");
                tel = Long.valueOf(tr);
                           tr = txtsalariofunc.getText();
                 tr = tr.replace(".", "");
        tr = tr.replace(",", ".");   
                sal = Float.valueOf(tr);
                 tr = txtcomfunc.getText();
                 tr = tr.replace(".", "");
        tr = tr.replace(",", "."); 
                comi = Float.valueOf(tr); 
                peri = (String) comboboxperfunc.getSelectedItem(); 
                email = txtemaifunc.getText();
        
        Conectar.carregarDriver();
      
      try { 
               
                   
               
            Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url2, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(GUICadfuncionario.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

             String sql;
   if (alteracaofuncionario == true){
    sql = "UPDATE funcionario SET func_cpf="+cpf+",func_rg="+rg+",func_ctps="+ctps+",func_nome='"+nome+"',func_dtnasc='"+dtnasc+"',func_end='"+end+"',func_bairro='"+bairro+"',func_compl='"+compl+"',func_cep="+cep+",func_tel="+tel+",func_sal="+sal+",func_comi="+comi+",func_peri='"+peri+"',func_email='"+email+"' WHERE func_cod="+cod+";";
    } else{ 
       sql = "INSERT INTO funcionario(func_cod,func_cpf,func_rg,func_ctps,func_nome,func_dtnasc,func_end,func_bairro,func_compl,func_cep,func_tel,func_sal,func_comi,func_peri,func_email) values(null,"+cpf+","+rg+","+ctps+",'"+nome+"','"+dtnasc+"','"+end+"','"+bairro+"','"+compl+"',"+cep+","+tel+","+sal+","+comi+",'"+peri+"','"+email+"')";
   }
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção
       if (alteracaofuncionario == true){
         JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso!!","",-1);
         alteracaofuncionario = false;
         new GUIPesquisarFuncionario().setVisible(true);
         this.dispose();
} else{
  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                txtcpffunc.setText("");
                txtrgfunc.setText("");
                txtctpsfunc.setText("");
                txttelfunc.setText("");
                txtnomefunc.setText("");
                datanascfunc.setDate(null);
                txtendfunc.setText("");
                txtbairrofunc.setText("");
                txtcompfunc.setText("");
                txtemaifunc.setText("");
                txtsalariofunc.setText("");
                txtcomfunc.setText("0,00");
                comboboxperfunc.setSelectedItem(null);
                txtemaifunc.setText("");
                txtcepfunc.setText("");
                
                if (pegarfunc == true){
    new GUIPesquisarFuncionario().setVisible(true);
    this.dispose();    
}
                
       }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!"+ ex,"ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente", erro + "ERRO",0);
            
        }
    }//GEN-LAST:event_bttcadastrarfuncionarioActionPerformed

    private void bttlimparfuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttlimparfuncionarioActionPerformed
         txtcpffunc.setText("");
                txtrgfunc.setText("");
                txtctpsfunc.setText("");
                txttelfunc.setText("");
                txtnomefunc.setText("");
                datanascfunc.setDate(null);
                txtendfunc.setText("");
                txtbairrofunc.setText("");
                txtcompfunc.setText("");
                txtemaifunc.setText("");
                txtsalariofunc.setText("");
                txtcomfunc.setText("0,00");
                comboboxperfunc.setSelectedItem(null);
                txtemaifunc.setText("");
                txtcepfunc.setText("");
    }//GEN-LAST:event_bttlimparfuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICadfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICadfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICadfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadfuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICadfuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttcadastrarfuncionario;
    private javax.swing.JButton bttlimparfuncionario;
    private javax.swing.JButton bttvoltarmenupesquisar;
    private javax.swing.JComboBox comboboxperfunc;
    private com.toedter.calendar.JDateChooser datanascfunc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelbairrofunc;
    private javax.swing.JLabel labelcepfunc;
    private javax.swing.JLabel labelcomifunc;
    private javax.swing.JLabel labelcomplfunc;
    private javax.swing.JLabel labelcpfcliente1;
    private javax.swing.JLabel labelcpffunc;
    private javax.swing.JLabel labeldtnasfunc;
    private javax.swing.JLabel labelemailfunc;
    private javax.swing.JLabel labelendfunc;
    private javax.swing.JLabel labelimgpro;
    private javax.swing.JLabel labelnomefunc;
    private javax.swing.JLabel labelperfunc;
    private javax.swing.JLabel labelrgfunc;
    private javax.swing.JLabel labelsalariofunc;
    private javax.swing.JLabel labeltelfunc;
    private javax.swing.JLabel lblselecionar;
    private javax.swing.JTextField txtbairrofunc;
    private javax.swing.JFormattedTextField txtcepfunc;
    private javax.swing.JFormattedTextField txtcomfunc;
    private javax.swing.JTextField txtcompfunc;
    private javax.swing.JFormattedTextField txtcpffunc;
    private javax.swing.JTextField txtctpsfunc;
    private javax.swing.JTextField txtemaifunc;
    private javax.swing.JTextField txtendfunc;
    private javax.swing.JTextField txtnomefunc;
    private javax.swing.JFormattedTextField txtrgfunc;
    private javax.swing.JFormattedTextField txtsalariofunc;
    private javax.swing.JFormattedTextField txttelfunc;
    // End of variables declaration//GEN-END:variables
}
