/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import Controler.Conectar;
import static View.GUIPesquisarContas.alteracaocontas;
import static View.GUIPesquisarContas.pesqcontascod;
import static View.GUIPesquisarContas.pesqcontasdesc;
import static View.GUIPesquisarContas.pesqcontasdte;
import static View.GUIPesquisarContas.pesqcontasdtvenc;
import static View.GUIPesquisarContas.pesqcontasncobra;
import static View.GUIPesquisarContas.pesqcontasobs;
import static View.GUIPesquisarContas.pesqcontassaca;
import static View.GUIPesquisarContas.pesqcontasstatus;
import static View.GUIPesquisarContas.pesqcontastipo;
import static View.GUIPesquisarContas.pesqcontasvalor;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author lab0519
 */
public class GUICadContas extends javax.swing.JFrame {

    static String dte;
    static String dtvenc;
    static String saca;
    static String cobra;
    static String tipo;
    static float valor;
    static String status;
    static String desc;
    static String obs;
    static int cod;
    
    String url2 = "jdbc:mysql://localhost/loja"; // enderço do BD
  String username = "root";        //nome de um usuário de seu BD
  String password = "";  // senha do BD
    
    
    public GUICadContas() {
     Model.LookAndFeel.estilo();         initComponents();
        
             this.setDefaultCloseOperation(2);     
              this.setResizable(false);   this.setTitle("FaciModas 1.0"); 
              DecimalFormat dFormat = new DecimalFormat("#,###,###.00") ;
        NumberFormatter formatter = new NumberFormatter(dFormat) ;
        formatter.setFormat(dFormat) ;
        formatter.setAllowsInvalid(false) ;      
        txtvalorcap.setFormatterFactory ( new DefaultFormatterFactory ( formatter ) ) ;
        
               if (alteracaocontas == true ){

DateFormat formate = new SimpleDateFormat("yyyy-dd-MM");
        Date dte=null, venc=null;
            try {
                dte = (java.util.Date) formate.parse(pesqcontasdte);
               
               venc = (java.util.Date) formate.parse(pesqcontasdtvenc);
            } catch (ParseException ex) {
                Logger.getLogger(GUICadContas.class.getName()).log(Level.SEVERE, null, ex);
            }
           

  dataemcap.setDate(dte);
                  datavenccap.setDate(venc);
                txtsacadocap.setText(pesqcontassaca);
                txttipocap.setText(pesqcontastipo);
                txtvalorcap.setText(pesqcontasvalor);
                comboboxstatuscap.setSelectedItem(pesqcontasstatus); 
                txtdesccap.setText(pesqcontasdesc);
                txtobscap.setText(pesqcontasobs);
                txtnumcap.setText(pesqcontasncobra);
        lblselecionar.setText("Alterar Conta");
       bttcadastrarcap.setText("Salvar");
 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbldataemcap = new javax.swing.JLabel();
        dataemcap = new com.toedter.calendar.JDateChooser();
        lbldatavencap = new javax.swing.JLabel();
        datavenccap = new com.toedter.calendar.JDateChooser();
        lblstatuscap = new javax.swing.JLabel();
        comboboxstatuscap = new javax.swing.JComboBox();
        lbnumcap = new javax.swing.JLabel();
        txtnumcap = new javax.swing.JTextField();
        lbltipocap = new javax.swing.JLabel();
        txttipocap = new javax.swing.JTextField();
        lblvalcap = new javax.swing.JLabel();
        lbldesccap = new javax.swing.JLabel();
        lblobscap = new javax.swing.JLabel();
        txtobscap = new javax.swing.JTextField();
        labelimg = new javax.swing.JLabel();
        txtsacadocap = new javax.swing.JTextField();
        lblsacadocap = new javax.swing.JLabel();
        bttcadastrarcap = new javax.swing.JButton();
        bttlimparcap = new javax.swing.JButton();
        txtdesccap = new javax.swing.JTextField();
        lblselecionar = new javax.swing.JLabel();
        bttvoltarmenupesquisar = new javax.swing.JButton();
        txtvalorcap = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        lbldataemcap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbldataemcap.setForeground(new java.awt.Color(255, 255, 255));
        lbldataemcap.setText("Data de emissão:");
        jPanel1.add(lbldataemcap);
        lbldataemcap.setBounds(320, 170, 130, 30);
        jPanel1.add(dataemcap);
        dataemcap.setBounds(420, 170, 140, 30);

        lbldatavencap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbldatavencap.setForeground(new java.awt.Color(255, 255, 255));
        lbldatavencap.setText("Data de vencimento:");
        jPanel1.add(lbldatavencap);
        lbldatavencap.setBounds(600, 170, 130, 30);
        jPanel1.add(datavenccap);
        datavenccap.setBounds(740, 170, 120, 30);

        lblstatuscap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblstatuscap.setForeground(new java.awt.Color(255, 255, 255));
        lblstatuscap.setText("Status:");
        jPanel1.add(lblstatuscap);
        lblstatuscap.setBounds(80, 170, 80, 30);

        comboboxstatuscap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pagar", "Receber" }));
        comboboxstatuscap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxstatuscapActionPerformed(evt);
            }
        });
        jPanel1.add(comboboxstatuscap);
        comboboxstatuscap.setBounds(150, 170, 140, 30);

        lbnumcap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbnumcap.setForeground(new java.awt.Color(255, 255, 255));
        lbnumcap.setText("N° Cobrança:");
        jPanel1.add(lbnumcap);
        lbnumcap.setBounds(470, 210, 100, 30);
        jPanel1.add(txtnumcap);
        txtnumcap.setBounds(570, 210, 290, 30);

        lbltipocap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbltipocap.setForeground(new java.awt.Color(255, 255, 255));
        lbltipocap.setText("Tipo:");
        jPanel1.add(lbltipocap);
        lbltipocap.setBounds(80, 250, 90, 30);
        jPanel1.add(txttipocap);
        txttipocap.setBounds(150, 250, 300, 30);

        lblvalcap.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblvalcap.setForeground(new java.awt.Color(255, 255, 255));
        lblvalcap.setText("Valor:");
        jPanel1.add(lblvalcap);
        lblvalcap.setBounds(80, 330, 60, 30);

        lbldesccap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbldesccap.setForeground(new java.awt.Color(255, 255, 255));
        lbldesccap.setText("Descrição:");
        jPanel1.add(lbldesccap);
        lbldesccap.setBounds(80, 290, 80, 30);

        lblobscap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblobscap.setForeground(new java.awt.Color(255, 255, 255));
        lblobscap.setText("Obs:");
        jPanel1.add(lblobscap);
        lblobscap.setBounds(80, 370, 60, 30);
        jPanel1.add(txtobscap);
        txtobscap.setBounds(150, 370, 710, 30);

        labelimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranco1.png"))); // NOI18N
        labelimg.setText("jLabel1");
        jPanel1.add(labelimg);
        labelimg.setBounds(-20, -10, 200, 120);
        jPanel1.add(txtsacadocap);
        txtsacadocap.setBounds(150, 210, 300, 30);

        lblsacadocap.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblsacadocap.setForeground(new java.awt.Color(255, 255, 255));
        lblsacadocap.setText("Cobrador:");
        jPanel1.add(lblsacadocap);
        lblsacadocap.setBounds(80, 210, 90, 30);

        bttcadastrarcap.setBackground(new java.awt.Color(0, 0, 0));
        bttcadastrarcap.setForeground(new java.awt.Color(255, 255, 255));
        bttcadastrarcap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconsave.png"))); // NOI18N
        bttcadastrarcap.setText("Cadastrar");
        bttcadastrarcap.setBorder(null);
        bttcadastrarcap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttcadastrarcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcadastrarcapActionPerformed(evt);
            }
        });
        jPanel1.add(bttcadastrarcap);
        bttcadastrarcap.setBounds(510, 450, 140, 30);

        bttlimparcap.setBackground(new java.awt.Color(0, 0, 0));
        bttlimparcap.setForeground(new java.awt.Color(255, 255, 255));
        bttlimparcap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconlimpar.png"))); // NOI18N
        bttlimparcap.setText("Limpar");
        bttlimparcap.setBorder(null);
        bttlimparcap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttlimparcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttlimparcapActionPerformed(evt);
            }
        });
        jPanel1.add(bttlimparcap);
        bttlimparcap.setBounds(360, 450, 140, 30);
        jPanel1.add(txtdesccap);
        txtdesccap.setBounds(150, 290, 710, 30);

        lblselecionar.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblselecionar.setForeground(new java.awt.Color(255, 255, 255));
        lblselecionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblselecionar.setText("Cadastrar Contas");
        lblselecionar.setToolTipText("");
        jPanel1.add(lblselecionar);
        lblselecionar.setBounds(140, 60, 720, 40);

        bttvoltarmenupesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltaresquerdanovo.jpg"))); // NOI18N
        bttvoltarmenupesquisar.setToolTipText("Voltar para o menu de pesquisas!");
        bttvoltarmenupesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bttvoltarmenupesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttvoltarmenupesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttvoltarmenupesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(bttvoltarmenupesquisar);
        bttvoltarmenupesquisar.setBounds(80, 490, 40, 40);
        jPanel1.add(txtvalorcap);
        txtvalorcap.setBounds(150, 330, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 570);

        setSize(new java.awt.Dimension(931, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttcadastrarcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcadastrarcapActionPerformed
       
        dte  = new SimpleDateFormat("yyyy-MM-dd").format(dataemcap.getDate());
        dtvenc  = new SimpleDateFormat("yyyy-MM-dd").format(dataemcap.getDate());
        saca = txtsacadocap.getText();
        tipo = txttipocap.getText();
        String tr = txtvalorcap.getText();
         tr = tr.replace(".", "");
        tr = tr.replace(",", ".");  
        valor = Float.valueOf(tr);
        status = comboboxstatuscap.getSelectedItem().toString();
        desc = txtdesccap.getText();
        obs = txtobscap.getText();
        cobra = txtnumcap.getText();
        
      Conectar.carregarDriver();
      
    if(comboboxstatuscap.getSelectedItem().equals("Pagar")){  
        
      try { 
               
                   
               
            Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url2, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(GUICadCliente.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

            // Recebendo os dados a serem inseridos na tabela
    
            String sql;
        
             if (alteracaocontas == true){
                  sql = "UPDATE contasapagar SET  cap_dte='"+dte+"',cap_dtvenc='"+dtvenc+"',cap_cobrador='"+saca+"',cap_ncobra='"+cobra+"',cap_tipo='"+tipo+"',cap_valor="+valor+",cap_status='"+status+"',cap_desc='"+desc+"',cap_obs='"+obs+"' WHERE cap_cod="+cod+";";

             }else{
            sql = "INSERT INTO contasapagar(cap_cod,cap_dte,cap_dtvenc,cap_cobrador,cap_ncobra,cap_tipo,cap_valor,cap_status,cap_desc,cap_obs) values(null,'"+dte+"','"+dtvenc+"','"+saca+"','"+cobra+"','"+tipo+"',"+valor+",'"+status+"','"+desc+"','"+obs+"')";
             }
             
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção
 if (alteracaocontas == true){
         JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso!!","",-1);
         alteracaocontas = false;
         new GUIPesquisarContas().setVisible(true);
         this.dispose();
} else{
  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                 dataemcap.setDate(null);
                datavenccap.setDate(null);
                txtsacadocap.setText("");
                txtnumcap.setText("");
                txttipocap.setText("");
                txtvalorcap.setText("0,00");
                comboboxstatuscap.setSelectedItem("Pagar"); 
                txtdesccap.setText("");
                txtobscap.setText("");
                txtdesccap.setText("");
                txtnumcap.setText("");
 }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!"+ex,"ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            
        }
      }
    if(comboboxstatuscap.getSelectedItem().equals("Receber")){  
        
      try { 
               
                   
               
            Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url2, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(GUICadCliente.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

            // Recebendo os dados a serem inseridos na tabela
    String sql;
      if (alteracaocontas == true){
                sql = "UPDATE contasareceber SET  car_dte='"+dte+"',car_dtvenc='"+dtvenc+"',car_sacado='"+saca+"',car_ncobra='"+cobra+"',car_tipo='"+tipo+"',car_valor="+valor+",car_status='"+status+"',car_desc='"+desc+"',car_obs='"+obs+"' WHERE car_cod="+cod+";";
             }else{
          sql = "INSERT INTO contasareceber(car_cod,car_dte,car_dtvenc,car_sacado,car_ncobra,car_tipo,car_valor,car_status,car_desc,car_obs) values(null,'"+dte+"','"+dtvenc+"','"+saca+"','"+cobra+"','"+tipo+"',"+valor+",'"+status+"','"+desc+"','"+obs+"')";
      }
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção
                
                 if (alteracaocontas == true){
         JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso!!","",-1);
         alteracaocontas = false;
         new GUIPesquisarContas().setVisible(true);
         this.dispose();
} else{
  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                dataemcap.setDate(null);
                datavenccap.setDate(null);
                txtsacadocap.setText("");
                txtnumcap.setText("");
                txttipocap.setText("");
                txtvalorcap.setText("0,0");
                comboboxstatuscap.setSelectedItem("Pagar"); 
                txtdesccap.setText("");
                txtobscap.setText("");
                txtdesccap.setText("");
                 }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro na inserção!"+ex,"ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            
        }
      }
    
    
    }//GEN-LAST:event_bttcadastrarcapActionPerformed

    private void comboboxstatuscapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxstatuscapActionPerformed
       
        if (comboboxstatuscap.getSelectedItem().toString().equals("Pagar")){
        
        lblsacadocap.setText("Cobrador:");
        
        }
        
            if (comboboxstatuscap.getSelectedItem().toString().equals("Receber")){
        
          lblsacadocap.setText("Sacado:");
        
        }
            
    }//GEN-LAST:event_comboboxstatuscapActionPerformed

    private void bttvoltarmenupesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttvoltarmenupesquisarActionPerformed
 if(alteracaocontas == true){
        new GUIPesquisarContas().setVisible(true);      this.dispose();    
        alteracaocontas = false;
}else{
        new GUICadastrarMenu().setVisible(true);       this.dispose(); 
 }// TODO add your handling code here:
    }//GEN-LAST:event_bttvoltarmenupesquisarActionPerformed

    private void bttlimparcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttlimparcapActionPerformed
       dataemcap.setDate(null);
                datavenccap.setDate(null);
                txtsacadocap.setText("");
                txttipocap.setText("");
                txtvalorcap.setText("0,00");
                comboboxstatuscap.setSelectedItem("Pagar"); 
                txtdesccap.setText("");
                txtobscap.setText("");
                txtdesccap.setText("");
    }//GEN-LAST:event_bttlimparcapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICadContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICadContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICadContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICadContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttcadastrarcap;
    private javax.swing.JButton bttlimparcap;
    private javax.swing.JButton bttvoltarmenupesquisar;
    private javax.swing.JComboBox comboboxstatuscap;
    private com.toedter.calendar.JDateChooser dataemcap;
    private com.toedter.calendar.JDateChooser datavenccap;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelimg;
    private javax.swing.JLabel lbldataemcap;
    private javax.swing.JLabel lbldatavencap;
    private javax.swing.JLabel lbldesccap;
    private javax.swing.JLabel lblobscap;
    private javax.swing.JLabel lblsacadocap;
    private javax.swing.JLabel lblselecionar;
    private javax.swing.JLabel lblstatuscap;
    private javax.swing.JLabel lbltipocap;
    private javax.swing.JLabel lblvalcap;
    private javax.swing.JLabel lbnumcap;
    private javax.swing.JTextField txtdesccap;
    private javax.swing.JTextField txtnumcap;
    private javax.swing.JTextField txtobscap;
    private javax.swing.JTextField txtsacadocap;
    private javax.swing.JTextField txttipocap;
    private javax.swing.JFormattedTextField txtvalorcap;
    // End of variables declaration//GEN-END:variables
}
