/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import Controler.Conectar;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 

/**
 *
 * @author Aluno Tarde
 */
public class GUICadEmpresa extends javax.swing.JFrame {

    static long cnpj;
    static long insc;
    static String nome;
    static long tel;
    static String site;
    static String email;
    
    String url2 = "jdbc:mysql://localhost/loja"; // enderço do BD
  String username = "root";        //nome de um usuário de seu BD
  String password = "";  // senha do BD
    String empcnpj, empinsc, empnome, emptel, empsite, empemail;
    static boolean dados = true;
    public GUICadEmpresa() {
     Model.LookAndFeel.estilo();         initComponents();
              this.setDefaultCloseOperation(2);      this.setResizable(false);   this.setTitle("FaciModas 1.0"); 
              
              
               try{    
            //Declarando a variavel código
           
   
                           
            Conectar.carregarDriver(); // Carregando o driver
            try {// Tratamento de erro para a conexao
                // Declarando  a variavel de conexão con
                // e estabelendo a conexão
                Connection con = null;

                try {
                    con = (Connection) DriverManager.getConnection(url2, username, password);
                } catch (SQLException ex) {
                    Logger.getLogger(GUIPesquisarCartao.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Declarando uma string com o comando mySQL para consulta
             String sql="";
                   

                      

         sql = "SELECT * FROM empresa;";
  

                      Statement stm = (Statement) con.createStatement();
                try
                {
                   
                    ResultSet rs = stm.executeQuery(sql);

                    int i=0; 

                    while (rs.next()) {  
                        
                        
                            
                        empcnpj = rs.getString("emp_cnpj");
                      empinsc= rs.getString("emp_insc");
                         empnome= rs.getString("emp_nome");
                         emptel= rs.getString("emp_tel");
                        empsite= rs.getString("emp_site");
                         empemail= rs.getString("emp_email");
                        
                             
                        i++;  
                                        }
                       if(i==0){ // Verificando se ha dados cadastrados atraves da variavel i

                        dados=false;
                    }else{
                      txtcnpjempresa.setText(empcnpj);
                      txtinscricaoempresa.setText(empinsc);
                      txtnomeempresa.setText(empnome);
                      txtemailempresa.setText(empemail);
                      txtsiteempresa.setText(empsite);
                      txttelempresa.setText(emptel);
                       dados = true;
                       }

                 

                } catch (Exception ex) { 
                    
                    
                    }

            } catch (SQLException ex) {
            
            }
        }catch(NumberFormatException erro){
         
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttlimparempresa = new javax.swing.JButton();
        bttcadastrarempresa = new javax.swing.JButton();
        labelimg = new javax.swing.JLabel();
        lblemailempresa = new javax.swing.JLabel();
        lbltelefoneempresa = new javax.swing.JLabel();
        lclcnpjempresa = new javax.swing.JLabel();
        lblincricaoempresa = new javax.swing.JLabel();
        txtinscricaoempresa = new javax.swing.JTextField();
        try

        {

            javax.swing.text.MaskFormatter ie= new 

            javax.swing.text.MaskFormatter("#########");

            txtinscricaoempresa = new javax.swing.JFormattedTextField(ie);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        lblnomemepresa = new javax.swing.JLabel();
        txtnomeempresa = new javax.swing.JTextField();
        lblsiteempresa = new javax.swing.JLabel();
        txtsiteempresa = new javax.swing.JTextField();
        txtemailempresa = new javax.swing.JTextField();
        lblselecionar = new javax.swing.JLabel();
        bttvoltarmenupesquisar = new javax.swing.JButton();
        txtcnpjempresa = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter cnpj= new 

            javax.swing.text.MaskFormatter("###.###.###/####-##");

            txtcnpjempresa = new javax.swing.JFormattedTextField(cnpj);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txttelempresa = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter tel= new 

            javax.swing.text.MaskFormatter("(##) ####-####");

            txttelempresa = new javax.swing.JFormattedTextField(tel);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        bttlimparempresa.setBackground(new java.awt.Color(0, 0, 0));
        bttlimparempresa.setForeground(new java.awt.Color(255, 255, 255));
        bttlimparempresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconlimpar.png"))); // NOI18N
        bttlimparempresa.setText("Limpar");
        bttlimparempresa.setBorder(null);
        bttlimparempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttlimparempresaActionPerformed(evt);
            }
        });
        jPanel1.add(bttlimparempresa);
        bttlimparempresa.setBounds(340, 430, 140, 30);

        bttcadastrarempresa.setBackground(new java.awt.Color(0, 0, 0));
        bttcadastrarempresa.setForeground(new java.awt.Color(255, 255, 255));
        bttcadastrarempresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconsave.png"))); // NOI18N
        bttcadastrarempresa.setText("Cadastrar");
        bttcadastrarempresa.setBorder(null);
        bttcadastrarempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcadastrarempresaActionPerformed(evt);
            }
        });
        jPanel1.add(bttcadastrarempresa);
        bttcadastrarempresa.setBounds(490, 430, 140, 30);

        labelimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranco1.png"))); // NOI18N
        labelimg.setText("jLabel1");
        jPanel1.add(labelimg);
        labelimg.setBounds(-20, -10, 200, 110);

        lblemailempresa.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblemailempresa.setForeground(new java.awt.Color(255, 255, 255));
        lblemailempresa.setText("Email:");
        jPanel1.add(lblemailempresa);
        lblemailempresa.setBounds(70, 270, 60, 30);

        lbltelefoneempresa.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbltelefoneempresa.setForeground(new java.awt.Color(255, 255, 255));
        lbltelefoneempresa.setText("Telefone:");
        jPanel1.add(lbltelefoneempresa);
        lbltelefoneempresa.setBounds(660, 270, 60, 30);

        lclcnpjempresa.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lclcnpjempresa.setForeground(new java.awt.Color(255, 255, 255));
        lclcnpjempresa.setText("CNPJ:");
        jPanel1.add(lclcnpjempresa);
        lclcnpjempresa.setBounds(70, 230, 90, 30);

        lblincricaoempresa.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblincricaoempresa.setForeground(new java.awt.Color(255, 255, 255));
        lblincricaoempresa.setText("Inscriçao Estadual:");
        jPanel1.add(lblincricaoempresa);
        lblincricaoempresa.setBounds(460, 230, 130, 30);
        jPanel1.add(txtinscricaoempresa);
        txtinscricaoempresa.setBounds(580, 230, 270, 30);

        lblnomemepresa.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblnomemepresa.setForeground(new java.awt.Color(255, 255, 255));
        lblnomemepresa.setText("Nome:");
        jPanel1.add(lblnomemepresa);
        lblnomemepresa.setBounds(70, 190, 50, 30);
        jPanel1.add(txtnomeempresa);
        txtnomeempresa.setBounds(140, 190, 710, 30);

        lblsiteempresa.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblsiteempresa.setForeground(new java.awt.Color(255, 255, 255));
        lblsiteempresa.setText("Site:");
        jPanel1.add(lblsiteempresa);
        lblsiteempresa.setBounds(70, 310, 60, 30);
        jPanel1.add(txtsiteempresa);
        txtsiteempresa.setBounds(140, 310, 710, 30);
        jPanel1.add(txtemailempresa);
        txtemailempresa.setBounds(140, 270, 500, 30);

        lblselecionar.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblselecionar.setForeground(new java.awt.Color(255, 255, 255));
        lblselecionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblselecionar.setText("Cadastrar Empresa");
        lblselecionar.setToolTipText("");
        jPanel1.add(lblselecionar);
        lblselecionar.setBounds(140, 60, 710, 40);

        bttvoltarmenupesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltaresquerdanovo.jpg"))); // NOI18N
        bttvoltarmenupesquisar.setToolTipText("Voltar para o menu de pesquisas!");
        bttvoltarmenupesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bttvoltarmenupesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttvoltarmenupesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttvoltarmenupesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(bttvoltarmenupesquisar);
        bttvoltarmenupesquisar.setBounds(80, 490, 40, 40);
        jPanel1.add(txtcnpjempresa);
        txtcnpjempresa.setBounds(140, 230, 260, 30);
        jPanel1.add(txttelempresa);
        txttelempresa.setBounds(720, 270, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(931, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttcadastrarempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcadastrarempresaActionPerformed
       String tr;
         tr = txtcnpjempresa.getText();
         tr = tr.replace("-", "");
         tr = tr.replace(".", "");
         tr = tr.replace("/", "");
        cnpj = Long.valueOf(tr);
      insc = Long.valueOf(txtinscricaoempresa.getText());
      nome = txtnomeempresa.getText();
         tr = txttelempresa.getText();
         tr = tr.replace("-", "");
         tr = tr.replace("(", "");
         tr = tr.replace(")", "");
           tr = tr.replace(" ", "");
      tel = Long.valueOf(tr);
      site = txtsiteempresa.getText();
      email = txtemailempresa.getText();
      
     

       Conectar.carregarDriver();
       
      try { 
               
                   
               
            Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url2, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(GUICadEmpresa.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

  String sql="";
    if (dados==false){
             sql = "INSERT INTO empresa(emp_cnpj,emp_insc,emp_nome,emp_tel,emp_site,emp_email) values("+cnpj+","+insc+",'"+nome+"',"+tel+",'"+site+"','"+email+"')";
    }else{
     sql = "UPDATE empresa SET emp_cnpj="+cnpj+",emp_insc="+insc+",emp_nome='"+nome+"',emp_tel="+tel+",emp_site='"+site+"',emp_email='"+email+"' WHERE emp_cnpj="+empcnpj+";";
   
    }
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção

  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
           
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!"+ex,"ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            
        }

       
              

    }//GEN-LAST:event_bttcadastrarempresaActionPerformed

    private void bttvoltarmenupesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttvoltarmenupesquisarActionPerformed
  this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bttvoltarmenupesquisarActionPerformed

    private void bttlimparempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttlimparempresaActionPerformed
    txtcnpjempresa.setText("");
                txtinscricaoempresa.setText("");
                txtnomeempresa.setText("");
                txtemailempresa.setText("");
                txtsiteempresa.setText("");
                txttelempresa.setText("");
    }//GEN-LAST:event_bttlimparempresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICadEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttcadastrarempresa;
    private javax.swing.JButton bttlimparempresa;
    private javax.swing.JButton bttvoltarmenupesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelimg;
    private javax.swing.JLabel lblemailempresa;
    private javax.swing.JLabel lblincricaoempresa;
    private javax.swing.JLabel lblnomemepresa;
    private javax.swing.JLabel lblselecionar;
    private javax.swing.JLabel lblsiteempresa;
    private javax.swing.JLabel lbltelefoneempresa;
    private javax.swing.JLabel lclcnpjempresa;
    private javax.swing.JFormattedTextField txtcnpjempresa;
    private javax.swing.JTextField txtemailempresa;
    private javax.swing.JTextField txtinscricaoempresa;
    private javax.swing.JTextField txtnomeempresa;
    private javax.swing.JTextField txtsiteempresa;
    private javax.swing.JFormattedTextField txttelempresa;
    // End of variables declaration//GEN-END:variables
}
