/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import Controler.Conectar;
import static View.GUIPesquisarClientes.alteracaocliente;
import static View.GUIPesquisarClientes.codigocliente;
import static View.GUIPesquisarClientes.pesqclibairro;
import static View.GUIPesquisarClientes.pesqclicep;
import static View.GUIPesquisarClientes.pesqclicompl;
import static View.GUIPesquisarClientes.pesqclicpf;
import static View.GUIPesquisarClientes.pesqclidtnasc;
import static View.GUIPesquisarClientes.pesqcliemail;
import static View.GUIPesquisarClientes.pesqcliend;
import static View.GUIPesquisarClientes.pesqclinome;
import static View.GUIPesquisarClientes.pesqclirg;
import static View.GUIPesquisarClientes.pesqclitel;
import static View.GUIVender.pegarcliente;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 

/**
 *
 * @author lab0519
 */
public class GUICadCliente extends javax.swing.JFrame {

    static long cpf;
    static long rg;
    static String nome;
    static String end;
    static int endn;
    static String bairro;
    static String compl;
    static int cep;
    static long tel;
    static String email;
    static String dtnasc;
    static int pontpromo;
    
    String url2 = "jdbc:mysql://localhost/loja"; // enderço do BD
  String username = "root";        //nome de um usuário de seu BD
  String password = "";  // senha do BD
static int cod;
    
    public GUICadCliente() {
     Model.LookAndFeel.estilo();         initComponents();
              this.setDefaultCloseOperation(2);      this.setResizable(false);   this.setTitle("FaciModas 1.0"); 
        if (alteracaocliente == true ){

DateFormat formate = new SimpleDateFormat("yyyy-dd-MM");
                    Date dtconvert=null;
            try {
   dtconvert = (java.util.Date) formate.parse(pesqclidtnasc);
               
                
            } catch (ParseException ex) {
                Logger.getLogger(GUICadCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
           

 cod = codigocliente;
     txtcpfcliente.setText(pesqclicpf);
     txtrgcliente.setText(pesqclirg);
      txtnomecliente.setText(pesqclinome);
      txtendcliente.setText(pesqcliend);
       txtbairrocliente.setText(pesqclibairro);
      txtcompcliente.setText(pesqclicompl);
        txtcepcliente.setText(pesqclicep);
       txttelcliente.setText(pesqclitel);
       txtemailcliente.setText(pesqcliemail);
       datanascliente.setDate(dtconvert);
        txtpromocliente.setText(pesqclirg);
        lbltitulo.setText("Alterar Cliente");
       bttcadastrarcli.setText("Salvar");
 }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelimg = new javax.swing.JLabel();
        labelcpfcliente = new javax.swing.JLabel();
        labeldtnascliente = new javax.swing.JLabel();
        labelnomecliente = new javax.swing.JLabel();
        labelendcliente = new javax.swing.JLabel();
        labelbairrocliente = new javax.swing.JLabel();
        labelcomplcliente = new javax.swing.JLabel();
        labeltelcliente = new javax.swing.JLabel();
        txtnomecliente = new javax.swing.JTextField();
        txtendcliente = new javax.swing.JTextField();
        txtbairrocliente = new javax.swing.JTextField();
        txtcompcliente = new javax.swing.JTextField();
        labelcepcliente = new javax.swing.JLabel();
        labelrgcliente = new javax.swing.JLabel();
        txtemailcliente = new javax.swing.JTextField();
        labelemailcliente = new javax.swing.JLabel();
        datanascliente = new com.toedter.calendar.JDateChooser();
        bttcadastrarcli = new javax.swing.JButton();
        bttlimparcli = new javax.swing.JButton();
        labelrgcliente1 = new javax.swing.JLabel();
        txtpromocliente = new javax.swing.JTextField();
        lbltitulo = new javax.swing.JLabel();
        bttvoltarmenupesquisar = new javax.swing.JButton();
        txtcpfcliente = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter cpf= new 

            javax.swing.text.MaskFormatter("###.###.###-##");

            txtcpfcliente = new javax.swing.JFormattedTextField(cpf);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txtrgcliente = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter rg= new 

            javax.swing.text.MaskFormatter("##.###.###-#");

            txtrgcliente = new javax.swing.JFormattedTextField(rg);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txtcepcliente = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter cep= new 

            javax.swing.text.MaskFormatter("#####-###");

            txtcepcliente = new javax.swing.JFormattedTextField(cep);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txttelcliente = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter tel= new 

            javax.swing.text.MaskFormatter("(##) ####-####");

            txttelcliente = new javax.swing.JFormattedTextField(tel);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        labelimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranco1.png"))); // NOI18N
        labelimg.setText("jLabel1");
        jPanel1.add(labelimg);
        labelimg.setBounds(-10, 0, 200, 110);

        labelcpfcliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcpfcliente.setForeground(new java.awt.Color(255, 255, 255));
        labelcpfcliente.setText("CPF:");
        jPanel1.add(labelcpfcliente);
        labelcpfcliente.setBounds(50, 220, 50, 30);

        labeldtnascliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labeldtnascliente.setForeground(new java.awt.Color(255, 255, 255));
        labeldtnascliente.setText("Data de nascimento:");
        jPanel1.add(labeldtnascliente);
        labeldtnascliente.setBounds(610, 220, 120, 30);

        labelnomecliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelnomecliente.setForeground(new java.awt.Color(255, 255, 255));
        labelnomecliente.setText("Nome :");
        jPanel1.add(labelnomecliente);
        labelnomecliente.setBounds(50, 180, 60, 30);

        labelendcliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelendcliente.setForeground(new java.awt.Color(255, 255, 255));
        labelendcliente.setText("Endereço: ");
        jPanel1.add(labelendcliente);
        labelendcliente.setBounds(50, 260, 60, 30);

        labelbairrocliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelbairrocliente.setForeground(new java.awt.Color(255, 255, 255));
        labelbairrocliente.setText("Bairro:");
        jPanel1.add(labelbairrocliente);
        labelbairrocliente.setBounds(650, 260, 60, 30);

        labelcomplcliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcomplcliente.setForeground(new java.awt.Color(255, 255, 255));
        labelcomplcliente.setText("Complemento:");
        jPanel1.add(labelcomplcliente);
        labelcomplcliente.setBounds(280, 300, 100, 30);

        labeltelcliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labeltelcliente.setForeground(new java.awt.Color(255, 255, 255));
        labeltelcliente.setText("Telefone:");
        jPanel1.add(labeltelcliente);
        labeltelcliente.setBounds(50, 340, 60, 30);
        jPanel1.add(txtnomecliente);
        txtnomecliente.setBounds(110, 180, 760, 30);
        jPanel1.add(txtendcliente);
        txtendcliente.setBounds(110, 260, 480, 30);
        jPanel1.add(txtbairrocliente);
        txtbairrocliente.setBounds(710, 260, 160, 30);
        jPanel1.add(txtcompcliente);
        txtcompcliente.setBounds(360, 300, 280, 30);

        labelcepcliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcepcliente.setForeground(new java.awt.Color(255, 255, 255));
        labelcepcliente.setText("CEP:");
        jPanel1.add(labelcepcliente);
        labelcepcliente.setBounds(50, 300, 60, 30);

        labelrgcliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelrgcliente.setForeground(new java.awt.Color(255, 255, 255));
        labelrgcliente.setText("RG:");
        jPanel1.add(labelrgcliente);
        labelrgcliente.setBounds(370, 220, 40, 30);
        jPanel1.add(txtemailcliente);
        txtemailcliente.setBounds(360, 340, 280, 30);

        labelemailcliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelemailcliente.setForeground(new java.awt.Color(255, 255, 255));
        labelemailcliente.setText("Email:");
        jPanel1.add(labelemailcliente);
        labelemailcliente.setBounds(280, 340, 60, 30);
        jPanel1.add(datanascliente);
        datanascliente.setBounds(730, 220, 140, 30);

        bttcadastrarcli.setBackground(new java.awt.Color(0, 0, 0));
        bttcadastrarcli.setForeground(new java.awt.Color(255, 255, 255));
        bttcadastrarcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconsave.png"))); // NOI18N
        bttcadastrarcli.setText("Cadastrar");
        bttcadastrarcli.setBorder(null);
        bttcadastrarcli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttcadastrarcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcadastrarcliActionPerformed(evt);
            }
        });
        jPanel1.add(bttcadastrarcli);
        bttcadastrarcli.setBounds(490, 440, 130, 30);

        bttlimparcli.setBackground(new java.awt.Color(0, 0, 0));
        bttlimparcli.setForeground(new java.awt.Color(255, 255, 255));
        bttlimparcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconlimpar.png"))); // NOI18N
        bttlimparcli.setText("Limpar");
        bttlimparcli.setBorder(null);
        bttlimparcli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttlimparcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttlimparcliActionPerformed(evt);
            }
        });
        jPanel1.add(bttlimparcli);
        bttlimparcli.setBounds(360, 440, 120, 30);

        labelrgcliente1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelrgcliente1.setForeground(new java.awt.Color(255, 255, 255));
        labelrgcliente1.setText("Pontos promocionais:");
        jPanel1.add(labelrgcliente1);
        labelrgcliente1.setBounds(650, 340, 120, 30);

        txtpromocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpromoclienteActionPerformed(evt);
            }
        });
        jPanel1.add(txtpromocliente);
        txtpromocliente.setBounds(770, 340, 100, 30);

        lbltitulo.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 255, 255));
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("Cadastrar Cliente");
        lbltitulo.setToolTipText("");
        jPanel1.add(lbltitulo);
        lbltitulo.setBounds(100, 60, 770, 40);

        bttvoltarmenupesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltaresquerdanovo.jpg"))); // NOI18N
        bttvoltarmenupesquisar.setToolTipText("Voltar para o menu de pesquisas!");
        bttvoltarmenupesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bttvoltarmenupesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttvoltarmenupesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttvoltarmenupesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(bttvoltarmenupesquisar);
        bttvoltarmenupesquisar.setBounds(60, 490, 40, 40);
        jPanel1.add(txtcpfcliente);
        txtcpfcliente.setBounds(110, 220, 240, 30);
        jPanel1.add(txtrgcliente);
        txtrgcliente.setBounds(400, 220, 190, 30);
        jPanel1.add(txtcepcliente);
        txtcepcliente.setBounds(110, 300, 140, 30);
        jPanel1.add(txttelcliente);
        txttelcliente.setBounds(110, 340, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 950, 570);

        setSize(new java.awt.Dimension(933, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttcadastrarcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcadastrarcliActionPerformed

  String tr = txtcpfcliente.getText();
        tr = tr.replace(".", "");
        tr = tr.replace("-", "");
        cpf = Long.valueOf(tr); 
        
         tr = txtrgcliente.getText();
        tr = tr.replace(".", "");
        tr = tr.replace("-", "");
      rg = Long.valueOf(tr); 
      nome = txtnomecliente.getText();
      end = txtendcliente.getText();
     bairro = txtbairrocliente.getText();
      compl = txtcompcliente.getText();
      
       tr = txtcepcliente.getText();
         tr = tr.replace("-", "");
      cep = Integer.valueOf(tr);
      
      tr = txttelcliente.getText();
         tr = tr.replace("-", "");
         tr = tr.replace("(", "");
         tr = tr.replace(")", "");
           tr = tr.replace(" ", "");
      tel =Long.valueOf(tr);
      email =txtemailcliente.getText();
      dtnasc = new SimpleDateFormat("yyyy-MM-dd").format(datanascliente.getDate());
      pontpromo = Integer.valueOf(txtpromocliente.getText());
      
      Conectar.carregarDriver();
      
      try { 
               
                   
               
            Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url2, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(GUICadCliente.class.getName()).log(Level.SEVERE, null, ex);
          
                   }
  String sql;
   if (alteracaocliente == true){
    sql = "UPDATE cliente SET  cli_cpf="+cpf+",cli_rg="+rg+",cli_nome='"+nome+"',cli_end='"+end+"',cli_bairro='"+bairro+"',cli_compl='"+compl+"',cli_cep="+cep+",cli_tel="+tel+",cli_email='"+email+"',cli_dtnasc='"+dtnasc+"',cli_pontpromo="+pontpromo+" WHERE cli_cod="+cod+";";
    } else{
           sql = "INSERT INTO cliente(cli_cod,cli_cpf,cli_rg,cli_nome,cli_end,cli_bairro,cli_compl,cli_cep,cli_tel,cli_email,cli_dtnasc,cli_pontpromo) values(null,"+cpf+","+rg+",'"+nome+"','"+end+"','"+bairro+"','"+compl+"',"+cep+","+tel+",'"+email+"','"+dtnasc+"',"+pontpromo+")";
   }
   
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção
                
                   if (alteracaocliente == true){
         JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso!!","",-1);
         alteracaocliente = false;
         new GUIPesquisarClientes().setVisible(true);
         this.dispose();
} else{

  JOptionPane.showMessageDialog(null,"Inserção realizada com sucesso!!","",-1);
  
                txtcpfcliente.setText("");
                txtrgcliente.setText("");
                txtnomecliente.setText("");
                txtendcliente.setText("");
                txtbairrocliente.setText("");
                txtcompcliente.setText("");
                txtcepcliente.setText("");
                txttelcliente.setText("");
                datanascliente.setDate(null);
                txtpromocliente.setText("");
                txtemailcliente.setText("");
                if(pegarcliente == true){
                    new GUIPesquisarClientes().setVisible(true);
                    this.dispose();
                }
                   }
                
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"Erro na inserção!"+ex,"ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            
        }

    }//GEN-LAST:event_bttcadastrarcliActionPerformed

    private void txtpromoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpromoclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpromoclienteActionPerformed

    private void bttvoltarmenupesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttvoltarmenupesquisarActionPerformed
if (pegarcliente == true){
            new GUIPesquisarClientes().setVisible(true);      this.dispose();    
    
}else{
    if(alteracaocliente == true){
        alteracaocliente = false;
        new GUIPesquisarClientes().setVisible(true);      this.dispose();    
}else{
        new GUICadastrarMenu().setVisible(true);       this.dispose();   
    }
}
    }//GEN-LAST:event_bttvoltarmenupesquisarActionPerformed

    private void bttlimparcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttlimparcliActionPerformed
         txtcpfcliente.setText("");
                txtrgcliente.setText("");
                txtnomecliente.setText("");
                txtendcliente.setText("");
                txtbairrocliente.setText("");
                txtcompcliente.setText("");
                txtcepcliente.setText("");
                txttelcliente.setText("");
                datanascliente.setDate(null);
                txtpromocliente.setText("");
                txtemailcliente.setText("");       
    }//GEN-LAST:event_bttlimparcliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttcadastrarcli;
    private javax.swing.JButton bttlimparcli;
    private javax.swing.JButton bttvoltarmenupesquisar;
    private com.toedter.calendar.JDateChooser datanascliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelbairrocliente;
    private javax.swing.JLabel labelcepcliente;
    private javax.swing.JLabel labelcomplcliente;
    private javax.swing.JLabel labelcpfcliente;
    private javax.swing.JLabel labeldtnascliente;
    private javax.swing.JLabel labelemailcliente;
    private javax.swing.JLabel labelendcliente;
    private javax.swing.JLabel labelimg;
    private javax.swing.JLabel labelnomecliente;
    private javax.swing.JLabel labelrgcliente;
    private javax.swing.JLabel labelrgcliente1;
    private javax.swing.JLabel labeltelcliente;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField txtbairrocliente;
    private javax.swing.JFormattedTextField txtcepcliente;
    private javax.swing.JTextField txtcompcliente;
    public static javax.swing.JFormattedTextField txtcpfcliente;
    private javax.swing.JTextField txtemailcliente;
    private javax.swing.JTextField txtendcliente;
    private javax.swing.JTextField txtnomecliente;
    private javax.swing.JTextField txtpromocliente;
    private javax.swing.JFormattedTextField txtrgcliente;
    private javax.swing.JFormattedTextField txttelcliente;
    // End of variables declaration//GEN-END:variables
}
