/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import Controler.Conectar;
import static View.GUIPesquisarProduto.alteracaoproduto;
import static View.GUIPesquisarProduto.codigoproduto;
import static View.GUIPesquisarProduto.pesqprodcate;
import static View.GUIPesquisarProduto.pesqprodcod;
import static View.GUIPesquisarProduto.pesqprodcodbarra;
import static View.GUIPesquisarProduto.pesqprodcor;
import static View.GUIPesquisarProduto.pesqprodmarca;
import static View.GUIPesquisarProduto.pesqprodmargem;
import static View.GUIPesquisarProduto.pesqprodnome;
import static View.GUIPesquisarProduto.pesqprodquant;
import static View.GUIPesquisarProduto.pesqprodtam;
import static View.GUIPesquisarProduto.pesqprodtaxatri;
import static View.GUIPesquisarProduto.pesqprodtipo;
import static View.GUIPesquisarProduto.pesqprodvlforn;
import static View.GUIPesquisarProduto.pesqprodvlvenda;
import static View.GUIVender.pegarproduto;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat; 
import java.util.Date; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author lab0519
 */
public class GUICadProduto extends javax.swing.JFrame {


    static String nome, codbarra;
    static String tipo;
    static String marca;
    static float valor, valorforn;

    static String cor;
    static String cate;
    static int quant;
     static String secao,tam;
    static float taxatri;
    static float margem;
    static int cod;
    String url2 = "jdbc:mysql://localhost/loja"; // enderço do BD
  String username = "root";        //nome de um usuário de seu BD
  String password = "";  // senha do BD
  
    public GUICadProduto() {
     Model.LookAndFeel.estilo();         initComponents();
        quantprod.setValue(1);
              this.setDefaultCloseOperation(2);     this.setResizable(false); 
              
               DecimalFormat dFormat = new DecimalFormat("#,###,###.00") ;
        NumberFormatter formatter = new NumberFormatter(dFormat) ;
        formatter.setFormat(dFormat) ;
        formatter.setAllowsInvalid(false) ;      
        txtvalfornprod.setFormatterFactory ( new DefaultFormatterFactory ( formatter ) ) ;
           txtvalprod.setFormatterFactory ( new DefaultFormatterFactory ( formatter ) ) ;
              txtmargemprod.setFormatterFactory ( new DefaultFormatterFactory ( formatter ) ) ;
         if (alteracaoproduto == true ){
           
 cod = Integer.valueOf(pesqprodcod); 
     txtnomeprod.setText(pesqprodnome);
               txtvalprod.setText(pesqprodvlvenda);
                txttamprod.setText(pesqprodtam);
                txtcorprod.setText(pesqprodcor);
               combocategoria.setSelectedItem(pesqprodcate);
               quantprod.setValue(Integer.valueOf(pesqprodquant));
                txtmargemprod.setText(pesqprodmargem);
                txttaxatriprod.setText(pesqprodtaxatri);
                txtmarca.setText(pesqprodmarca);
                txtvalfornprod.setText(pesqprodvlforn);
                txtcodbarra.setText(pesqprodcodbarra);
                combotipo.setSelectedItem(pesqprodtipo);
        lblselecionar.setText("Alterar Produto");
       bttcadastrarproduto.setText("Salvar");
 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblnomeprod = new javax.swing.JLabel();
        txtnomeprod = new javax.swing.JTextField();
        lblmarcaprod = new javax.swing.JLabel();
        lblcategoriaprod = new javax.swing.JLabel();
        lbltamanhoprod = new javax.swing.JLabel();
        labelendcliente = new javax.swing.JLabel();
        lblvalorprod = new javax.swing.JLabel();
        tbltaxatributariaprod = new javax.swing.JLabel();
        lblmargemprod = new javax.swing.JLabel();
        lbltipoprod = new javax.swing.JLabel();
        quantprod = new javax.swing.JSpinner();
        txttamprod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bttcadastrarproduto = new javax.swing.JButton();
        bttlimparproduto = new javax.swing.JButton();
        combocategoria = new javax.swing.JComboBox();
        lblcorprod = new javax.swing.JLabel();
        txtcorprod = new javax.swing.JTextField();
        txttaxatriprod = new javax.swing.JTextField();
        txtmarca = new javax.swing.JTextField();
        combotipo = new javax.swing.JComboBox();
        lblselecionar = new javax.swing.JLabel();
        lblvalorprod1 = new javax.swing.JLabel();
        lblvalorprod2 = new javax.swing.JLabel();
        txtcodbarra = new javax.swing.JTextField();
        bttvoltarmenupesquisar1 = new javax.swing.JButton();
        txtvalfornprod = new javax.swing.JFormattedTextField();
        txtvalprod = new javax.swing.JFormattedTextField();
        txtmargemprod = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        lblnomeprod.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblnomeprod.setForeground(new java.awt.Color(255, 255, 255));
        lblnomeprod.setText("Nome:");
        jPanel1.add(lblnomeprod);
        lblnomeprod.setBounds(40, 200, 60, 30);
        jPanel1.add(txtnomeprod);
        txtnomeprod.setBounds(150, 200, 320, 30);

        lblmarcaprod.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblmarcaprod.setForeground(new java.awt.Color(255, 255, 255));
        lblmarcaprod.setText("Marca:");
        jPanel1.add(lblmarcaprod);
        lblmarcaprod.setBounds(40, 240, 50, 30);

        lblcategoriaprod.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblcategoriaprod.setForeground(new java.awt.Color(255, 255, 255));
        lblcategoriaprod.setText("Categoria:");
        jPanel1.add(lblcategoriaprod);
        lblcategoriaprod.setBounds(650, 200, 80, 30);

        lbltamanhoprod.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbltamanhoprod.setForeground(new java.awt.Color(255, 255, 255));
        lbltamanhoprod.setText("Tamanhos:");
        jPanel1.add(lbltamanhoprod);
        lbltamanhoprod.setBounds(480, 240, 60, 30);

        labelendcliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelendcliente.setForeground(new java.awt.Color(255, 255, 255));
        labelendcliente.setText("Quantidade:");
        jPanel1.add(labelendcliente);
        labelendcliente.setBounds(300, 240, 80, 30);

        lblvalorprod.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblvalorprod.setForeground(new java.awt.Color(255, 255, 255));
        lblvalorprod.setText("Código de barras:");
        jPanel1.add(lblvalorprod);
        lblvalorprod.setBounds(40, 160, 110, 30);

        tbltaxatributariaprod.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tbltaxatributariaprod.setForeground(new java.awt.Color(255, 255, 255));
        tbltaxatributariaprod.setText("Taxa Tributária:");
        jPanel1.add(tbltaxatributariaprod);
        tbltaxatributariaprod.setBounds(40, 320, 100, 30);

        lblmargemprod.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblmargemprod.setForeground(new java.awt.Color(255, 255, 255));
        lblmargemprod.setText("Margem de lucro:");
        jPanel1.add(lblmargemprod);
        lblmargemprod.setBounds(40, 360, 120, 30);

        lbltipoprod.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbltipoprod.setForeground(new java.awt.Color(255, 255, 255));
        lbltipoprod.setText("Tipo:");
        jPanel1.add(lbltipoprod);
        lbltipoprod.setBounds(500, 200, 50, 30);
        jPanel1.add(quantprod);
        quantprod.setBounds(370, 240, 100, 30);

        txttamprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttamprodActionPerformed(evt);
            }
        });
        jPanel1.add(txttamprod);
        txttamprod.setBounds(540, 240, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranco1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-20, -10, 200, 120);

        bttcadastrarproduto.setBackground(new java.awt.Color(0, 0, 0));
        bttcadastrarproduto.setForeground(new java.awt.Color(255, 255, 255));
        bttcadastrarproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconsave.png"))); // NOI18N
        bttcadastrarproduto.setText("Cadastrar");
        bttcadastrarproduto.setBorder(null);
        bttcadastrarproduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttcadastrarproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcadastrarprodutoActionPerformed(evt);
            }
        });
        jPanel1.add(bttcadastrarproduto);
        bttcadastrarproduto.setBounds(480, 460, 130, 30);

        bttlimparproduto.setBackground(new java.awt.Color(0, 0, 0));
        bttlimparproduto.setForeground(new java.awt.Color(255, 255, 255));
        bttlimparproduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconlimpar.png"))); // NOI18N
        bttlimparproduto.setText("Limpar");
        bttlimparproduto.setBorder(null);
        bttlimparproduto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttlimparproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttlimparprodutoActionPerformed(evt);
            }
        });
        jPanel1.add(bttlimparproduto);
        bttlimparproduto.setBounds(340, 460, 130, 30);

        combocategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Feminino", "Masculino", "Infantil", "Outro" }));
        combocategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combocategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(combocategoria);
        combocategoria.setBounds(720, 200, 150, 30);

        lblcorprod.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblcorprod.setForeground(new java.awt.Color(255, 255, 255));
        lblcorprod.setText("Cor:");
        jPanel1.add(lblcorprod);
        lblcorprod.setBounds(680, 240, 30, 30);
        jPanel1.add(txtcorprod);
        txtcorprod.setBounds(720, 240, 150, 30);
        jPanel1.add(txttaxatriprod);
        txttaxatriprod.setBounds(150, 320, 140, 30);
        jPanel1.add(txtmarca);
        txtmarca.setBounds(150, 240, 140, 30);

        combotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Calçados", "Vestuários", "Acessórios", "Outros" }));
        jPanel1.add(combotipo);
        combotipo.setBounds(540, 200, 100, 30);

        lblselecionar.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblselecionar.setForeground(new java.awt.Color(255, 255, 255));
        lblselecionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblselecionar.setText("Cadastrar Produto");
        lblselecionar.setToolTipText("");
        jPanel1.add(lblselecionar);
        lblselecionar.setBounds(100, 60, 780, 40);

        lblvalorprod1.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        lblvalorprod1.setForeground(new java.awt.Color(255, 255, 255));
        lblvalorprod1.setText("Preço de venda:");
        jPanel1.add(lblvalorprod1);
        lblvalorprod1.setBounds(40, 400, 140, 30);

        lblvalorprod2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lblvalorprod2.setForeground(new java.awt.Color(255, 255, 255));
        lblvalorprod2.setText("Preço fornecedor:");
        jPanel1.add(lblvalorprod2);
        lblvalorprod2.setBounds(40, 280, 110, 30);
        jPanel1.add(txtcodbarra);
        txtcodbarra.setBounds(150, 160, 140, 30);

        bttvoltarmenupesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltaresquerdanovo.jpg"))); // NOI18N
        bttvoltarmenupesquisar1.setToolTipText("Voltar para o menu de pesquisas!");
        bttvoltarmenupesquisar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bttvoltarmenupesquisar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttvoltarmenupesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttvoltarmenupesquisar1ActionPerformed(evt);
            }
        });
        jPanel1.add(bttvoltarmenupesquisar1);
        bttvoltarmenupesquisar1.setBounds(40, 480, 40, 40);
        jPanel1.add(txtvalfornprod);
        txtvalfornprod.setBounds(150, 280, 140, 30);
        jPanel1.add(txtvalprod);
        txtvalprod.setBounds(150, 400, 140, 30);
        jPanel1.add(txtmargemprod);
        txtmargemprod.setBounds(150, 360, 140, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(931, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttcadastrarprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcadastrarprodutoActionPerformed
      nome = txtnomeprod.getText(); 
      tipo = combotipo.getSelectedItem().toString();
      marca = txtmarca.getText();
           String tr = txtvalprod.getText();
         tr = tr.replace(".", "");
        tr = tr.replace(",", ".");   
      valor = Float.valueOf(tr);
      tam = txttamprod.getText();
      cor = txtcorprod.getText();
      cate = (String) combocategoria.getSelectedItem();
      quant = Integer.parseInt(quantprod.getValue().toString());
      
   tr = txttaxatriprod.getText();
         tr = tr.replace(".", "");
        tr = tr.replace(",", ".");   
      taxatri = Float.valueOf(tr);
      tr = txtmargemprod.getText();
         tr = tr.replace(".", "");
        tr = tr.replace(",", ".");  
      margem = Float.valueOf(tr);
      tr = txtvalfornprod.getText();
         tr = tr.replace(".", "");
        tr = tr.replace(",", ".");  
      valorforn = Float.valueOf(tr);
      codbarra = txtcodbarra.getText();
      Conectar.carregarDriver();
      
      try { 
               
                   
               
            Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url2, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(GUICadProduto.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

 String sql;
   if (alteracaoproduto == true){
    sql = "UPDATE produto SET  prod_nome='"+nome+"',prod_tipo='"+tipo+"',prod_marca='"+marca+"',prod_vlvenda="+valor+",prod_vlforn="+valorforn+",prod_tam='"+tam+"',prod_cor='"+cor+"',prod_cate='"+cate+"',prod_quant="+quant+",prod_taxatri="+taxatri+",prod_margem="+margem+" WHERE prod_cod="+cod+";";
    } else{       
       sql = "INSERT INTO produto(prod_cod,prod_codbarra,prod_nome,prod_tipo,prod_marca,prod_vlvenda,prod_vlforn,prod_tam,prod_cor,prod_cate,prod_quant,prod_taxatri,prod_margem) values(null,'"+codbarra+"','"+nome+"','"+tipo+"','"+marca+"',"+valor+","+valorforn+",'"+tam+"','"+cor+"','"+cate+"',"+quant+","+taxatri+","+margem+");";
   }
     
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção
     
                   if (alteracaoproduto == true){
         JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso!!","",-1);
         alteracaoproduto = false;
         new GUIPesquisarProduto().setVisible(true);
         this.dispose();
} else{
  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
       
                txtnomeprod.setText("");
                txtvalprod.setText("0,00");
                txttamprod.setText("");
                txtcorprod.setText("");
                combocategoria.setSelectedItem(null);
                quantprod.setValue(1);
                txttaxatriprod.setText("");
                txtmargemprod.setText("");
                txttaxatriprod.setText("");
                txtmarca.setText("");
                txtvalfornprod.setText("");
                txtcodbarra.setText("");
                 combotipo.setSelectedItem(null);
                 if (pegarproduto == true){
                     new GUIPesquisarProduto().setVisible(true);
                     this.dispose();
                                      }
                   }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            
        }
    }//GEN-LAST:event_bttcadastrarprodutoActionPerformed

    private void combocategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combocategoriaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_combocategoriaActionPerformed

    private void bttlimparprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttlimparprodutoActionPerformed
         txtnomeprod.setText("");
                 txtvalprod.setText("0,00");
                txttamprod.setText("");
                txtcorprod.setText("");
                combocategoria.setSelectedItem(null);
                quantprod.setValue(1);
                txttaxatriprod.setText("");
                txtmargemprod.setText("");
                txttaxatriprod.setText("");
                txtmarca.setText("");
                txtvalfornprod.setText("");
                txtcodbarra.setText("");
    }//GEN-LAST:event_bttlimparprodutoActionPerformed

    private void txttamprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttamprodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttamprodActionPerformed

    private void bttvoltarmenupesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttvoltarmenupesquisar1ActionPerformed
   if (pegarproduto == true){
        new GUIPesquisarProduto().setVisible(true);
      
   }else{
        if(alteracaoproduto == true){
        new GUIPesquisarProduto().setVisible(true);      this.dispose();    
        alteracaoproduto =false;
}else{

          new GUICadastrarMenu().setVisible(true); this.dispose();
   }
   }// TODO add your handling code here:
    }//GEN-LAST:event_bttvoltarmenupesquisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICadProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttcadastrarproduto;
    private javax.swing.JButton bttlimparproduto;
    private javax.swing.JButton bttvoltarmenupesquisar1;
    private javax.swing.JComboBox combocategoria;
    private javax.swing.JComboBox combotipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelendcliente;
    private javax.swing.JLabel lblcategoriaprod;
    private javax.swing.JLabel lblcorprod;
    private javax.swing.JLabel lblmarcaprod;
    private javax.swing.JLabel lblmargemprod;
    private javax.swing.JLabel lblnomeprod;
    private javax.swing.JLabel lblselecionar;
    private javax.swing.JLabel lbltamanhoprod;
    private javax.swing.JLabel lbltipoprod;
    private javax.swing.JLabel lblvalorprod;
    private javax.swing.JLabel lblvalorprod1;
    private javax.swing.JLabel lblvalorprod2;
    private javax.swing.JSpinner quantprod;
    private javax.swing.JLabel tbltaxatributariaprod;
    private javax.swing.JTextField txtcodbarra;
    private javax.swing.JTextField txtcorprod;
    private javax.swing.JTextField txtmarca;
    private javax.swing.JFormattedTextField txtmargemprod;
    private javax.swing.JTextField txtnomeprod;
    private javax.swing.JTextField txttamprod;
    private javax.swing.JTextField txttaxatriprod;
    private javax.swing.JFormattedTextField txtvalfornprod;
    private javax.swing.JFormattedTextField txtvalprod;
    // End of variables declaration//GEN-END:variables
}
