/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controler.Conectar;
import static View.GUIPesquisarCartao.alteracaocartao;
import static View.GUIPesquisarCartao.codigocartao;
import static View.GUIPesquisarCartao.pesqcartaocpf;
import static View.GUIPesquisarCartao.pesqcartaodtnasc;
import static View.GUIPesquisarCartao.pesqcartaoestacivil;
import static View.GUIPesquisarCartao.pesqcartaogrufi;
import static View.GUIPesquisarCartao.pesqcartaonome;
import static View.GUIPesquisarCartao.pesqcartaonum;
import static View.GUIPesquisarCartao.pesqcartaoval;
import static View.GUIPesquisarUsuario.alteracaousuario;
import static View.GUIPesquisarUsuario.codigousuario;
import static View.GUIPesquisarUsuario.pesquserfunccod;
import static View.GUIPesquisarUsuario.pesquserlogin;
import static View.GUIPesquisarUsuario.pesquserpass;
import static View.GUIPesquisarUsuario.pesqusertipo;
import com.mysql.jdbc.PreparedStatement;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author lab0519
 */
public class GUICadUsuario extends javax.swing.JFrame {


   String url2 = "jdbc:mysql://localhost/loja"; // enderço do BD
  String username = "root";        //nome de um usuário de seu BD
  String password = "";  // senha do BD
            static int cod;
  static String userlogin,userpass,usertipo;
  static int userfunccod, usercod;
  static boolean pegarfunc;
    public GUICadUsuario() {
     Model.LookAndFeel.estilo();         initComponents();
              this.setDefaultCloseOperation(2);      this.setResizable(false);   this.setTitle("FaciModas 1.0"); 

        
if (alteracaousuario == true ){
cod = codigousuario;
                txtfunccod.setText(pesquserfunccod);
         txtuser.setText(pesquserlogin);
        txtpass.setText(pesquserpass);
         combotipo.setSelectedItem(pesqusertipo) ;
        lblselecionar.setText("Alterar Usuário");
       bttcadastrarcartao.setText("Salvar");
 }

   


}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cartsexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        labelimg = new javax.swing.JLabel();
        labelcodcliente = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        labeldtnascliente = new javax.swing.JLabel();
        labelnomecliente1 = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox();
        bttcadastrarcartao = new javax.swing.JButton();
        bttlimparcartao = new javax.swing.JButton();
        lblselecionar = new javax.swing.JLabel();
        labelnomecliente2 = new javax.swing.JLabel();
        bttvoltarmenupesquisar = new javax.swing.JButton();
        txtpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        labelimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranco1.png"))); // NOI18N
        labelimg.setText("jLabel1");
        jPanel1.add(labelimg);
        labelimg.setBounds(-20, -20, 200, 140);

        labelcodcliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcodcliente.setForeground(new java.awt.Color(255, 255, 255));
        labelcodcliente.setText("Senha:");
        jPanel1.add(labelcodcliente);
        labelcodcliente.setBounds(170, 250, 90, 30);

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        jPanel1.add(txtuser);
        txtuser.setBounds(230, 210, 280, 30);

        labeldtnascliente.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labeldtnascliente.setForeground(new java.awt.Color(255, 255, 255));
        labeldtnascliente.setText("Tipo:");
        jPanel1.add(labeldtnascliente);
        labeldtnascliente.setBounds(530, 210, 90, 30);

        labelnomecliente1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelnomecliente1.setForeground(new java.awt.Color(255, 255, 255));
        labelnomecliente1.setText("Código do funcionário: ");
        jPanel1.add(labelnomecliente1);
        labelnomecliente1.setBounds(530, 250, 130, 30);

        combotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Padrão", "Administrador" }));
        jPanel1.add(combotipo);
        combotipo.setBounds(660, 210, 140, 30);

        bttcadastrarcartao.setBackground(new java.awt.Color(0, 0, 0));
        bttcadastrarcartao.setForeground(new java.awt.Color(255, 255, 255));
        bttcadastrarcartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconsave.png"))); // NOI18N
        bttcadastrarcartao.setText("Cadastrar");
        bttcadastrarcartao.setBorder(null);
        bttcadastrarcartao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttcadastrarcartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcadastrarcartaoActionPerformed(evt);
            }
        });
        jPanel1.add(bttcadastrarcartao);
        bttcadastrarcartao.setBounds(500, 390, 140, 30);

        bttlimparcartao.setBackground(new java.awt.Color(0, 0, 0));
        bttlimparcartao.setForeground(new java.awt.Color(255, 255, 255));
        bttlimparcartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconlimpar.png"))); // NOI18N
        bttlimparcartao.setText("Limpar");
        bttlimparcartao.setBorder(null);
        bttlimparcartao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttlimparcartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttlimparcartaoActionPerformed(evt);
            }
        });
        jPanel1.add(bttlimparcartao);
        bttlimparcartao.setBounds(350, 390, 140, 30);

        lblselecionar.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblselecionar.setForeground(new java.awt.Color(255, 255, 255));
        lblselecionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblselecionar.setText("Cadastrar Usuário");
        lblselecionar.setToolTipText("");
        jPanel1.add(lblselecionar);
        lblselecionar.setBounds(120, 60, 750, 40);

        labelnomecliente2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelnomecliente2.setForeground(new java.awt.Color(255, 255, 255));
        labelnomecliente2.setText("Usuário");
        jPanel1.add(labelnomecliente2);
        labelnomecliente2.setBounds(170, 210, 60, 30);
        jPanel1.add(txtfunccod);
        txtfunccod.setBounds(660, 250, 110, 30);

        bttvoltarmenupesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltaresquerdanovo.jpg"))); // NOI18N
        bttvoltarmenupesquisar.setToolTipText("Voltar para o menu de pesquisas!");
        bttvoltarmenupesquisar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bttvoltarmenupesquisar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttvoltarmenupesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttvoltarmenupesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(bttvoltarmenupesquisar);
        bttvoltarmenupesquisar.setBounds(70, 470, 40, 40);
        jPanel1.add(txtpass);
        txtpass.setBounds(230, 250, 280, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconpesquisar3.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(770, 250, 40, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 940, 570);

        setSize(new java.awt.Dimension(931, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttcadastrarcartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcadastrarcartaoActionPerformed

        if (txtuser.getText().equals("") || txtpass.getText().equals("") || txtfunccod.getText().equals("")){       
        JOptionPane.showMessageDialog(null,"Preencha todos os campos corretamente!");
}else{
          usertipo = (String) combotipo.getSelectedItem();
         userlogin = txtuser.getText();
   userpass = txtpass.getText();
            userfunccod = Integer.valueOf(txtfunccod.getText());
         Conectar.carregarDriver();
      
      try { 
               
                   
               
            Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url2, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(GUICadUsuario.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

            // Recebendo os dados a serem inseridos na tabela
            String sql;
             if (alteracaousuario == true){
          sql = "UPDATE usuario SET  user_login='"+userlogin+"',user_pass='"+userpass+"',user_func_cod="+userfunccod+",user_tipo='"+usertipo+"' WHERE user_cod="+cod+";";
    } else{
            sql= "INSERT INTO usuario(user_cod,user_login,user_pass,user_func_cod,user_tipo) values(null,'"+userlogin+"','"+userpass+"',"+userfunccod+",'"+usertipo+"')";
             }
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção
 if (alteracaousuario == true){
         JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso!!","",-1);
         alteracaousuario = false;
         new GUIPesquisarUsuario().setVisible(true);
         this.dispose();
} else{
  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
             
                txtfunccod.setText("");

         txtuser.setText("");
txtpass.setText("");
                 combotipo.setSelectedItem(null) ;
                
 }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            
        }
}
      
    }//GEN-LAST:event_bttcadastrarcartaoActionPerformed

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void bttlimparcartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttlimparcartaoActionPerformed
           
                txtfunccod.setText("");     
         txtuser.setText("");
         txtpass.setText("");
         combotipo.setSelectedItem(null) ;
    }//GEN-LAST:event_bttlimparcartaoActionPerformed

    private void bttvoltarmenupesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttvoltarmenupesquisarActionPerformed
        alteracaousuario = false;    
        new GUIPesquisarUsuario().setVisible(true);     
            this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_bttvoltarmenupesquisarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pegarfunc=true;
        new GUIPesquisarFuncionario().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICadUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttcadastrarcartao;
    private javax.swing.JButton bttlimparcartao;
    private javax.swing.JButton bttvoltarmenupesquisar;
    private javax.swing.ButtonGroup cartsexo;
    private javax.swing.JComboBox combotipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelcodcliente;
    private javax.swing.JLabel labeldtnascliente;
    private javax.swing.JLabel labelimg;
    private javax.swing.JLabel labelnomecliente1;
    private javax.swing.JLabel labelnomecliente2;
    private javax.swing.JLabel lblselecionar;
    public static final javax.swing.JTextField txtfunccod = new javax.swing.JTextField();
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
