/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

/**
 *
 * @author lab0519
 */
public class GUICadastrarMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUICadastrarMenu
     */
    public GUICadastrarMenu() {
     Model.LookAndFeel.estilo();         initComponents();   
           this.setDefaultCloseOperation(2);      this.setResizable(false);   this.setTitle("FaciModas 1.0"); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblimg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bttselecioneprodutopesq = new javax.swing.JButton();
        bttselecionecontascad1 = new javax.swing.JButton();
        bttselecioneclientepesq = new javax.swing.JButton();
        bttselecionefornecedorcad = new javax.swing.JButton();
        bttselecionefuncionariocad = new javax.swing.JButton();
        bttselecionecartcad = new javax.swing.JButton();
        bttvoltarmenupesquisar1 = new javax.swing.JButton();
        lblselecionar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setFocusable(false);
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.setLayout(null);

        lblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranco1.png"))); // NOI18N
        lblimg.setText("jLabel1");
        lblimg.setFocusable(false);
        lblimg.setRequestFocusEnabled(false);
        lblimg.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblimg);
        lblimg.setBounds(-20, -10, 200, 120);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Produto");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setFocusable(false);
        jLabel2.setInheritsPopupMenu(false);
        jLabel2.setRequestFocusEnabled(false);
        jLabel2.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(260, 130, 130, 170);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cartão");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setFocusable(false);
        jLabel1.setInheritsPopupMenu(false);
        jLabel1.setRequestFocusEnabled(false);
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 310, 130, 170);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Contas");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setFocusable(false);
        jLabel6.setInheritsPopupMenu(false);
        jLabel6.setRequestFocusEnabled(false);
        jLabel6.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 310, 130, 170);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fornecedor");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setFocusable(false);
        jLabel4.setInheritsPopupMenu(false);
        jLabel4.setRequestFocusEnabled(false);
        jLabel4.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(540, 310, 130, 170);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Funcionário");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setFocusable(false);
        jLabel5.setInheritsPopupMenu(false);
        jLabel5.setRequestFocusEnabled(false);
        jLabel5.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(540, 130, 130, 170);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cliente");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setFocusable(false);
        jLabel3.setInheritsPopupMenu(false);
        jLabel3.setRequestFocusEnabled(false);
        jLabel3.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(400, 130, 130, 170);

        bttselecioneprodutopesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/saltoalto.png"))); // NOI18N
        bttselecioneprodutopesq.setBorder(null);
        bttselecioneprodutopesq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttselecioneprodutopesq.setFocusable(false);
        bttselecioneprodutopesq.setOpaque(false);
        bttselecioneprodutopesq.setRequestFocusEnabled(false);
        bttselecioneprodutopesq.setVerifyInputWhenFocusTarget(false);
        bttselecioneprodutopesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttselecioneprodutopesqActionPerformed(evt);
            }
        });
        jPanel1.add(bttselecioneprodutopesq);
        bttselecioneprodutopesq.setBounds(270, 150, 110, 110);

        bttselecionecontascad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/contas.jpg"))); // NOI18N
        bttselecionecontascad1.setBorder(null);
        bttselecionecontascad1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttselecionecontascad1.setFocusable(false);
        bttselecionecontascad1.setOpaque(false);
        bttselecionecontascad1.setRequestFocusEnabled(false);
        bttselecionecontascad1.setVerifyInputWhenFocusTarget(false);
        bttselecionecontascad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttselecionecontascad1ActionPerformed(evt);
            }
        });
        jPanel1.add(bttselecionecontascad1);
        bttselecionecontascad1.setBounds(270, 340, 110, 110);

        bttselecioneclientepesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/addcli.jpg"))); // NOI18N
        bttselecioneclientepesq.setBorder(null);
        bttselecioneclientepesq.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttselecioneclientepesq.setFocusable(false);
        bttselecioneclientepesq.setOpaque(false);
        bttselecioneclientepesq.setRequestFocusEnabled(false);
        bttselecioneclientepesq.setVerifyInputWhenFocusTarget(false);
        bttselecioneclientepesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttselecioneclientepesqActionPerformed(evt);
            }
        });
        jPanel1.add(bttselecioneclientepesq);
        bttselecioneclientepesq.setBounds(400, 150, 120, 110);

        bttselecionefornecedorcad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fornecedor.jpg"))); // NOI18N
        bttselecionefornecedorcad.setBorder(null);
        bttselecionefornecedorcad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttselecionefornecedorcad.setFocusable(false);
        bttselecionefornecedorcad.setOpaque(false);
        bttselecionefornecedorcad.setRequestFocusEnabled(false);
        bttselecionefornecedorcad.setVerifyInputWhenFocusTarget(false);
        bttselecionefornecedorcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttselecionefornecedorcadActionPerformed(evt);
            }
        });
        jPanel1.add(bttselecionefornecedorcad);
        bttselecionefornecedorcad.setBounds(540, 340, 120, 110);

        bttselecionefuncionariocad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/addhom.jpg"))); // NOI18N
        bttselecionefuncionariocad.setBorder(null);
        bttselecionefuncionariocad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttselecionefuncionariocad.setFocusable(false);
        bttselecionefuncionariocad.setOpaque(false);
        bttselecionefuncionariocad.setRequestFocusEnabled(false);
        bttselecionefuncionariocad.setVerifyInputWhenFocusTarget(false);
        bttselecionefuncionariocad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttselecionefuncionariocadActionPerformed(evt);
            }
        });
        jPanel1.add(bttselecionefuncionariocad);
        bttselecionefuncionariocad.setBounds(540, 150, 120, 110);

        bttselecionecartcad.setBackground(new java.awt.Color(0, 0, 0));
        bttselecionecartcad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/card1.jpg"))); // NOI18N
        bttselecionecartcad.setBorder(null);
        bttselecionecartcad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttselecionecartcad.setFocusable(false);
        bttselecionecartcad.setOpaque(false);
        bttselecionecartcad.setRequestFocusEnabled(false);
        bttselecionecartcad.setVerifyInputWhenFocusTarget(false);
        bttselecionecartcad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttselecionecartcadActionPerformed(evt);
            }
        });
        jPanel1.add(bttselecionecartcad);
        bttselecionecartcad.setBounds(400, 340, 130, 110);

        bttvoltarmenupesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltaresquerdanovo.jpg"))); // NOI18N
        bttvoltarmenupesquisar1.setToolTipText("Voltar para o menu de pesquisas!");
        bttvoltarmenupesquisar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bttvoltarmenupesquisar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttvoltarmenupesquisar1.setFocusable(false);
        bttvoltarmenupesquisar1.setOpaque(false);
        bttvoltarmenupesquisar1.setRequestFocusEnabled(false);
        bttvoltarmenupesquisar1.setVerifyInputWhenFocusTarget(false);
        bttvoltarmenupesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttvoltarmenupesquisar1ActionPerformed(evt);
            }
        });
        jPanel1.add(bttvoltarmenupesquisar1);
        bttvoltarmenupesquisar1.setBounds(30, 500, 40, 40);

        lblselecionar.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblselecionar.setForeground(new java.awt.Color(255, 255, 255));
        lblselecionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblselecionar.setText("Cadastrar");
        lblselecionar.setFocusable(false);
        lblselecionar.setRequestFocusEnabled(false);
        lblselecionar.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblselecionar);
        lblselecionar.setBounds(0, 40, 910, 60);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(930, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttselecionecartcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttselecionecartcadActionPerformed
        new GUICadCartao().setVisible(true);   this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_bttselecionecartcadActionPerformed

    private void bttselecioneprodutopesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttselecioneprodutopesqActionPerformed
        new GUICadProduto().setVisible(true);   this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_bttselecioneprodutopesqActionPerformed

    private void bttselecionecontascad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttselecionecontascad1ActionPerformed
        new GUICadContas().setVisible(true);   this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_bttselecionecontascad1ActionPerformed

    private void bttselecioneclientepesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttselecioneclientepesqActionPerformed
        new GUICadCliente().setVisible(true);   this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_bttselecioneclientepesqActionPerformed

    private void bttselecionefornecedorcadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttselecionefornecedorcadActionPerformed
        new GUICadFornecedor().setVisible(true);   this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_bttselecionefornecedorcadActionPerformed

    private void bttselecionefuncionariocadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttselecionefuncionariocadActionPerformed
        new GUICadfuncionario().setVisible(true);   this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_bttselecionefuncionariocadActionPerformed

    private void bttvoltarmenupesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttvoltarmenupesquisar1ActionPerformed
    this.dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_bttvoltarmenupesquisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICadastrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICadastrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICadastrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadastrarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICadastrarMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttselecionecartcad;
    private javax.swing.JButton bttselecioneclientepesq;
    private javax.swing.JButton bttselecionecontascad1;
    private javax.swing.JButton bttselecionefornecedorcad;
    private javax.swing.JButton bttselecionefuncionariocad;
    private javax.swing.JButton bttselecioneprodutopesq;
    private javax.swing.JButton bttvoltarmenupesquisar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblimg;
    private javax.swing.JLabel lblselecionar;
    // End of variables declaration//GEN-END:variables
}
