/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;
import Controler.Conectar;
import static View.GUIPesquisarFornecedor.alteracaofornecedor;
import static View.GUIPesquisarFornecedor.codigofornecedor;
import static View.GUIPesquisarFornecedor.pesqfornbairro;
import static View.GUIPesquisarFornecedor.pesqforncep;
import static View.GUIPesquisarFornecedor.pesqforncnpj;
import static View.GUIPesquisarFornecedor.pesqforncompl;
import static View.GUIPesquisarFornecedor.pesqfornemail;
import static View.GUIPesquisarFornecedor.pesqfornend;
import static View.GUIPesquisarFornecedor.pesqfornie;
import static View.GUIPesquisarFornecedor.pesqfornrasoci;
import static View.GUIPesquisarFornecedor.pesqforntel;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import javax.swing.JOptionPane; 


/**
 *
 * @author lab0519
 */
public class GUICadFornecedor extends javax.swing.JFrame {

    
 static long cnpj;
 static String rasoci;
 static String end;
 static int endn, ie;
 static String bairro;
 static String compl;
 static long cep;
 static long tel;
 static String email;
   static int cod;
  String url2 = "jdbc:mysql://localhost/loja"; // enderço do BD
  String username = "root";        //nome de um usuário de seu BD
  String password = "";  // senha do BD

    
    public GUICadFornecedor() {
     Model.LookAndFeel.estilo();         initComponents();
              this.setDefaultCloseOperation(2);      this.setResizable(false);   this.setTitle("FaciModas 1.0"); 
        if (alteracaofornecedor == true ){

       

 cod = codigofornecedor;
    txtcnpjforn.setText(pesqforncnpj);
                txtrazaosocialforn.setText(pesqfornrasoci);
                txtieforn.setText(pesqfornie);
                txtendforn.setText(pesqfornend);
                txtbairroforn.setText(pesqfornbairro);
                txtcompforn.setText(pesqforncompl);
                txtcepforn.setText(pesqforncep);
                txttelforn.setText(pesqforntel);
                txtemailforn.setText(pesqfornemail);
        lblselecionar.setText("Alterar Fornecedor");
       bttcadastrarfornecedor.setText("Salvar");
 }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelrazaosocialforn = new javax.swing.JLabel();
        txtrazaosocialforn = new javax.swing.JTextField();
        labelcnpjforn = new javax.swing.JLabel();
        labelendforn = new javax.swing.JLabel();
        txtendforn = new javax.swing.JTextField();
        labelbairroforn = new javax.swing.JLabel();
        txtbairroforn = new javax.swing.JTextField();
        labelcomplforn = new javax.swing.JLabel();
        txtcompforn = new javax.swing.JTextField();
        labelcepforn = new javax.swing.JLabel();
        labeltelforn = new javax.swing.JLabel();
        labelemaiforn = new javax.swing.JLabel();
        txtemailforn = new javax.swing.JTextField();
        bttcadastrarfornecedor = new javax.swing.JButton();
        bttlimparfornecedor = new javax.swing.JButton();
        txtieforn = new javax.swing.JTextField();
        try

        {

            javax.swing.text.MaskFormatter ie= new 

            javax.swing.text.MaskFormatter("#########");

            txtieforn = new javax.swing.JFormattedTextField(ie);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        labelcnpjforn1 = new javax.swing.JLabel();
        lblselecionar = new javax.swing.JLabel();
        bttvoltarmenupesquisar1 = new javax.swing.JButton();
        txtcepforn = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter cep= new 

            javax.swing.text.MaskFormatter("#####-###");

            txtcepforn = new javax.swing.JFormattedTextField(cep);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txtcnpjforn = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter cnpj= new 

            javax.swing.text.MaskFormatter("###.###.###/####-##");

            txtcnpjforn = new javax.swing.JFormattedTextField(cnpj);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }
        txttelforn = new javax.swing.JFormattedTextField();
        try

        {

            javax.swing.text.MaskFormatter tel= new 

            javax.swing.text.MaskFormatter("(##) ####-####");

            txttelforn = new javax.swing.JFormattedTextField(tel);

        }

        catch (Exception e)

        {     

            JOptionPane.showMessageDialog(null,"Ocorreu um erro");//mensagem se acontecer erro

        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranco1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-20, -20, 180, 140);

        labelrazaosocialforn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelrazaosocialforn.setForeground(new java.awt.Color(255, 255, 255));
        labelrazaosocialforn.setText("Razão Social:");
        jPanel1.add(labelrazaosocialforn);
        labelrazaosocialforn.setBounds(50, 180, 100, 30);
        jPanel1.add(txtrazaosocialforn);
        txtrazaosocialforn.setBounds(130, 180, 740, 30);

        labelcnpjforn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcnpjforn.setForeground(new java.awt.Color(255, 255, 255));
        labelcnpjforn.setText("Insrição estadual:");
        jPanel1.add(labelcnpjforn);
        labelcnpjforn.setBounds(560, 220, 110, 30);

        labelendforn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelendforn.setForeground(new java.awt.Color(255, 255, 255));
        labelendforn.setText("Endereço: ");
        jPanel1.add(labelendforn);
        labelendforn.setBounds(50, 260, 60, 30);
        jPanel1.add(txtendforn);
        txtendforn.setBounds(130, 260, 320, 30);

        labelbairroforn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelbairroforn.setForeground(new java.awt.Color(255, 255, 255));
        labelbairroforn.setText("Bairro:");
        jPanel1.add(labelbairroforn);
        labelbairroforn.setBounds(620, 260, 60, 30);
        jPanel1.add(txtbairroforn);
        txtbairroforn.setBounds(670, 260, 200, 30);

        labelcomplforn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcomplforn.setForeground(new java.awt.Color(255, 255, 255));
        labelcomplforn.setText("Complemento:");
        jPanel1.add(labelcomplforn);
        labelcomplforn.setBounds(50, 300, 100, 30);
        jPanel1.add(txtcompforn);
        txtcompforn.setBounds(130, 300, 220, 30);

        labelcepforn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcepforn.setForeground(new java.awt.Color(255, 255, 255));
        labelcepforn.setText("CEP:");
        jPanel1.add(labelcepforn);
        labelcepforn.setBounds(470, 260, 60, 30);

        labeltelforn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labeltelforn.setForeground(new java.awt.Color(255, 255, 255));
        labeltelforn.setText("Telefone:");
        jPanel1.add(labeltelforn);
        labeltelforn.setBounds(50, 340, 60, 30);

        labelemaiforn.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelemaiforn.setForeground(new java.awt.Color(255, 255, 255));
        labelemaiforn.setText("Email:");
        jPanel1.add(labelemaiforn);
        labelemaiforn.setBounds(470, 340, 60, 30);
        jPanel1.add(txtemailforn);
        txtemailforn.setBounds(510, 340, 360, 30);

        bttcadastrarfornecedor.setBackground(new java.awt.Color(0, 0, 0));
        bttcadastrarfornecedor.setForeground(new java.awt.Color(255, 255, 255));
        bttcadastrarfornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconsave.png"))); // NOI18N
        bttcadastrarfornecedor.setText("Cadastrar");
        bttcadastrarfornecedor.setBorder(null);
        bttcadastrarfornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttcadastrarfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcadastrarfornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(bttcadastrarfornecedor);
        bttcadastrarfornecedor.setBounds(500, 450, 130, 30);

        bttlimparfornecedor.setBackground(new java.awt.Color(0, 0, 0));
        bttlimparfornecedor.setForeground(new java.awt.Color(255, 255, 255));
        bttlimparfornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconlimpar.png"))); // NOI18N
        bttlimparfornecedor.setText("Limpar");
        bttlimparfornecedor.setBorder(null);
        bttlimparfornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttlimparfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttlimparfornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(bttlimparfornecedor);
        bttlimparfornecedor.setBounds(370, 450, 120, 30);
        jPanel1.add(txtieforn);
        txtieforn.setBounds(670, 220, 200, 30);

        labelcnpjforn1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        labelcnpjforn1.setForeground(new java.awt.Color(255, 255, 255));
        labelcnpjforn1.setText("CNPJ:");
        jPanel1.add(labelcnpjforn1);
        labelcnpjforn1.setBounds(50, 220, 50, 30);

        lblselecionar.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblselecionar.setForeground(new java.awt.Color(255, 255, 255));
        lblselecionar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblselecionar.setText("Cadastrar Fornecedor");
        lblselecionar.setToolTipText("");
        jPanel1.add(lblselecionar);
        lblselecionar.setBounds(120, 60, 750, 40);

        bttvoltarmenupesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltaresquerdanovo.jpg"))); // NOI18N
        bttvoltarmenupesquisar1.setToolTipText("Voltar para o menu de pesquisas!");
        bttvoltarmenupesquisar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bttvoltarmenupesquisar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttvoltarmenupesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttvoltarmenupesquisar1ActionPerformed(evt);
            }
        });
        jPanel1.add(bttvoltarmenupesquisar1);
        bttvoltarmenupesquisar1.setBounds(60, 490, 40, 40);
        jPanel1.add(txtcepforn);
        txtcepforn.setBounds(509, 260, 100, 30);
        jPanel1.add(txtcnpjforn);
        txtcnpjforn.setBounds(130, 220, 220, 30);
        jPanel1.add(txttelforn);
        txttelforn.setBounds(130, 340, 220, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(931, 599));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttcadastrarfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcadastrarfornecedorActionPerformed
        String tr = txtcnpjforn.getText();
        tr = tr.replace(".", "");
        tr = tr.replace("-", "");
                tr = tr.replace("/", "");
                
        cnpj = Long.valueOf(tr); 
        
      rasoci = txtrazaosocialforn.getText(); 
      end = txtendforn.getText();
      bairro = txtbairroforn.getText();
      compl = txtcompforn.getText();
      
      tr = txtcepforn.getText();
    
        tr = tr.replace("-", "");
  
      cep = Long.valueOf(tr);
      tr = txttelforn.getText();
        tr = tr.replace(" ", "");
        tr = tr.replace("-", "");
                tr = tr.replace("(", "");
                   tr = tr.replace(")", "");
      tel = Integer.valueOf(tr);
      email = txtemailforn.getText();
      ie = Integer.parseInt(txtieforn.getText());
      
      Conectar.carregarDriver();
      
      
      
      try { 
               
                   
               
            Connection con = null;
            
            
    try {
    con = (Connection) DriverManager.getConnection(url2, username, password);
    } catch (SQLException ex) {

    Logger.getLogger(GUICadFornecedor.class.getName()).log(Level.SEVERE, null, ex);

            
                   }

          String sql;
   if (alteracaofornecedor == true){
    sql = "UPDATE fornecedor SET  forn_cnpj='"+cnpj+"',forn_ie='"+ie+"',forn_rasoci='"+rasoci+"',forn_end='"+end+"',forn_bairro='"+bairro+"',forn_compl='"+compl+"',forn_cep='"+cep+"',forn_tel='"+tel+"',forn_email='"+email+"' WHERE forn_cod="+cod+";";
    } else{
             sql = "INSERT INTO fornecedor(forn_cod,forn_cnpj,forn_ie,forn_rasoci,forn_end,forn_bairro,forn_compl,forn_cep,forn_tel,forn_email) values(null, "+cnpj+","+ie+",'"+rasoci+"','"+end+"','"+bairro+"','"+compl+"',"+cep+","+tel+",'"+email+"')";
   }
            try { // Tratamento de Erros para inserção

                // Criando varialvel que executara a inserção
                PreparedStatement inserir = (PreparedStatement) con.prepareStatement(sql);
                inserir.execute(); // Executando a inserção
             if (alteracaofornecedor == true){
         JOptionPane.showMessageDialog(null,"Alteração realizada com sucesso!!","",-1);
         alteracaofornecedor = false;
         new GUIPesquisarFornecedor().setVisible(true);
         this.dispose();
} else{
  JOptionPane.showMessageDialog(null,"\nInserção realizada com sucesso!!!\n","",-1);
                txtcnpjforn.setText("");
                txtrazaosocialforn.setText("");
                txtieforn.setText("");
                txtendforn.setText("");
                txtbairroforn.setText("");
                txtcompforn.setText("");
                txtcepforn.setText("");
                txttelforn.setText("");
                txtemailforn.setText("");
             }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,"\nErro na inserção!"+ex,"ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Tratamento de erro caso o usuario não digite o telefone corretamente
            JOptionPane.showMessageDialog(null,"Digite os dados corretamente","ERRO",0);
            
        }

       
              


    }//GEN-LAST:event_bttcadastrarfornecedorActionPerformed

    private void bttlimparfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttlimparfornecedorActionPerformed
        txtcnpjforn.setText("");
                txtrazaosocialforn.setText("");
                txtieforn.setText("");
                txtendforn.setText("");
                txtbairroforn.setText("");
                txtcompforn.setText("");
                txtcepforn.setText("");
                txttelforn.setText("");
                txtemailforn.setText("");
    }//GEN-LAST:event_bttlimparfornecedorActionPerformed

    private void bttvoltarmenupesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttvoltarmenupesquisar1ActionPerformed
 if(alteracaofornecedor == true){
        new GUIPesquisarFornecedor().setVisible(true);      this.dispose();   
        alteracaofornecedor = false;
}else{
     new GUICadastrarMenu().setVisible(true);
    this.dispose();
 }// TODO add your handling code here:
    }//GEN-LAST:event_bttvoltarmenupesquisar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICadFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICadFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttcadastrarfornecedor;
    private javax.swing.JButton bttlimparfornecedor;
    private javax.swing.JButton bttvoltarmenupesquisar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelbairroforn;
    private javax.swing.JLabel labelcepforn;
    private javax.swing.JLabel labelcnpjforn;
    private javax.swing.JLabel labelcnpjforn1;
    private javax.swing.JLabel labelcomplforn;
    private javax.swing.JLabel labelemaiforn;
    private javax.swing.JLabel labelendforn;
    private javax.swing.JLabel labelrazaosocialforn;
    private javax.swing.JLabel labeltelforn;
    private javax.swing.JLabel lblselecionar;
    private javax.swing.JTextField txtbairroforn;
    private javax.swing.JFormattedTextField txtcepforn;
    private javax.swing.JFormattedTextField txtcnpjforn;
    private javax.swing.JTextField txtcompforn;
    private javax.swing.JTextField txtemailforn;
    private javax.swing.JTextField txtendforn;
    private javax.swing.JTextField txtieforn;
    private javax.swing.JTextField txtrazaosocialforn;
    private javax.swing.JFormattedTextField txttelforn;
    // End of variables declaration//GEN-END:variables
}
