/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controler.Conectar;
import static Controler.TCC.pesquisa;
import static Controler.TCC.refresh;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno Tard
 */
public class GUIPesquisarContas extends javax.swing.JFrame {

static String lugar,palavra,coluna,coluna2;
static boolean alteracaocontas;
   String url2 = "jdbc:mysql://localhost/loja"; // enderço do BD
  String username = "root";        //nome de um usuário de seu BD
  String password = "";  // senha do BD
 static String  pesqcontascod, pesqcontasdte, pesqcontasdtvenc, pesqcontassaca, pesqcontasncobra, pesqcontastipo, pesqcontasvalor,pesqcontasstatus,pesqcontasdesc,pesqcontasobs; 
                 
    public GUIPesquisarContas() {
     Model.LookAndFeel.estilo();         initComponents();
              this.setDefaultCloseOperation(2);      this.setResizable(false);   this.setTitle("FaciModas 1.0"); 
               for (int indice=0; indice < tabela.getColumnCount(); indice++){
tabela.getColumnModel().getColumn(indice).setPreferredWidth(150);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("loja?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        contasapagarQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Contasapagar c");
        contasapagarList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : contasapagarQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtpesquisa = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        combotipo = new javax.swing.JComboBox();
        bttvoltarmenupesquisar9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logobranco1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-20, -10, 200, 111);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contas");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 850, 40);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tabela.setAutoscrolls(false);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, contasapagarList, tabela);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capCod}"));
        columnBinding.setColumnName("Código");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capDte}"));
        columnBinding.setColumnName("Emissão");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capDtvenc}"));
        columnBinding.setColumnName("Vencimento");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capCobrador}"));
        columnBinding.setColumnName("Cobrador");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capNcobra}"));
        columnBinding.setColumnName("Nº Cobrança");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capTipo}"));
        columnBinding.setColumnName("Tipo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capValor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(Float.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capStatus}"));
        columnBinding.setColumnName("Status");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capDesc}"));
        columnBinding.setColumnName("Descrição");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${capObs}"));
        columnBinding.setColumnName("Obs");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tabela);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 150, 850, 350);

        jButton1.setBackground(java.awt.Color.black);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconexcluir.png"))); // NOI18N
        jButton1.setText("Excluir");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(510, 110, 70, 30);

        jButton2.setBackground(java.awt.Color.black);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconedit2.png"))); // NOI18N
        jButton2.setText("Alterar");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(410, 110, 90, 30);

        txtpesquisa.setFont(new java.awt.Font("Calibri", 0, 11)); // NOI18N
        txtpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisaActionPerformed(evt);
            }
        });
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyReleased(evt);
            }
        });
        jPanel1.add(txtpesquisa);
        txtpesquisa.setBounds(590, 110, 260, 30);

        jButton3.setBackground(java.awt.Color.black);
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconpesquisar3.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(850, 110, 40, 30);

        combotipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pagar", "Receber" }));
        combotipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotipoActionPerformed(evt);
            }
        });
        jPanel1.add(combotipo);
        combotipo.setBounds(40, 110, 110, 30);

        bttvoltarmenupesquisar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/voltaresquerdanovo.jpg"))); // NOI18N
        bttvoltarmenupesquisar9.setToolTipText("Voltar para o menu de pesquisas!");
        bttvoltarmenupesquisar9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        bttvoltarmenupesquisar9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bttvoltarmenupesquisar9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttvoltarmenupesquisar9ActionPerformed(evt);
            }
        });
        jPanel1.add(bttvoltarmenupesquisar9);
        bttvoltarmenupesquisar9.setBounds(40, 510, 40, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 930, 580);

        bindingGroup.bind();

        setSize(new java.awt.Dimension(931, 600));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combotipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotipoActionPerformed
        String tipo = combotipo.getSelectedItem().toString();

        if(tipo.equals("Pagar")){
            lugar = "contasapagar";
       
        }

        if(tipo.equals("Receber")){
            lugar= "contasareceber";
        }
        refresh(tabela,lugar);
    }//GEN-LAST:event_combotipoActionPerformed

    private void txtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyPressed
    
        
        
    }//GEN-LAST:event_txtpesquisaKeyPressed

    private void txtpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisaActionPerformed

    private void txtpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyReleased
String tipo = combotipo.getSelectedItem().toString();
        
        palavra = txtpesquisa.getText();
        
    
        
    
            if(tipo.equals("Pagar")){
            coluna = "cap_cobrador";
            coluna2="cap_cod";
           lugar = "contasapagar";
              if(palavra.equals("")){
                          refresh(tabela,lugar);
              }else{
                      pesquisa(tabela,lugar,coluna,coluna2,palavra);
               }
        }

        if(tipo.equals("Receber")){
            coluna= "car_sacado";
             coluna2="car_cod";
              lugar= "contasareceber";
               if(palavra.equals("")){
                          refresh(tabela,lugar);
              }else{
                      pesquisa(tabela,lugar,coluna,coluna2,palavra);
               }
        }
    }//GEN-LAST:event_txtpesquisaKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
  String tipo = combotipo.getSelectedItem().toString();
        
        palavra = txtpesquisa.getText();
        
    
        
    
            if(tipo.equals("Pagar")){
            coluna = "cap_cobrador";
            coluna2="cap_cod";
           lugar = "contasapagar";
              if(palavra.equals("")){
                          refresh(tabela,lugar);
              }else{
                      pesquisa(tabela,lugar,coluna,coluna2,palavra);
               }
        }

        if(tipo.equals("Receber")){
            coluna= "car_sacado";
             coluna2="car_cod";
              lugar= "contasareceber";
               if(palavra.equals("")){
                          refresh(tabela,lugar);
              }else{
                      pesquisa(tabela,lugar,coluna,coluna2,palavra);
               }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int codigo;
                         if (txtpesquisa.getText().equals("") || txtpesquisa.getText() ==null){
                   
              codigo = (int) tabela.getValueAt(tabela.getSelectedRow(), 0);     
              
            }else{
                   if(tabela.getRowCount() == 1){
                    codigo = (int) tabela.getValueAt(0,0);
                    
                }else{
                        codigo = Integer.valueOf(txtpesquisa.getText());
            }                 
               }
      
        try{    
            //Declarando a variavel código
           
   
                           
            Conectar.carregarDriver(); // Carregando o driver
            try {// Tratamento de erro para a conexao
                // Declarando  a variavel de conexão con
                // e estabelendo a conexão
                Connection con = null;

                try {
                    con = (Connection) DriverManager.getConnection(url2, username, password);
                } catch (SQLException ex) {
                    Logger.getLogger(GUIPesquisarContas.class.getName()).log(Level.SEVERE, null, ex);
                }

                // Declarando uma string com o comando mySQL para consulta
             String sql="";
                      String tipo = combotipo.getSelectedItem().toString();

                      
        if(tipo.equals("Pagar")){
         sql = "SELECT cap_cod,cap_dte,cap_dtvenc,cap_cobrador,cap_ncobra,cap_tipo,cap_valor,cap_status,cap_desc,cap_obs FROM contasapagar where cap_cod = "+codigo+";";
                   }

        if(tipo.equals("Receber")){
         sql = "SELECT car_cod,car_dte,car_dtvenc,car_sacado,car_ncobra,car_tipo,car_valor,car_status,car_desc,car_obs FROM contasareceber where car_cod = "+codigo+";";
        }
               

                Statement stm = (Statement) con.createStatement();
                try
                {
                   
                    ResultSet rs = stm.executeQuery(sql);

                    int i=0; 

                    while (rs.next()) {  
                        
                            if(tipo.equals("Pagar")){
                                         pesqcontascod= rs.getString("cap_cod");
                        pesqcontasdte= rs.getString("cap_dte");
                        pesqcontasdtvenc= rs.getString("cap_dtvenc");
                        pesqcontassaca= rs.getString("cap_cobrador");
                        pesqcontasncobra= rs.getString("cap_ncobra");
                        pesqcontastipo= rs.getString("cap_tipo");
                        pesqcontasvalor= rs.getString("cap_valor");
                        pesqcontasstatus= rs.getString("cap_status");
                        pesqcontasdesc= rs.getString("cap_desc");
                        pesqcontasobs= rs.getString("cap_obs");
              }

        if(tipo.equals("Receber")){
          pesqcontascod= rs.getString("car_cod");
                        pesqcontasdte= rs.getString("car_dte");
                        pesqcontasdtvenc= rs.getString("car_dtvenc");
                        pesqcontassaca= rs.getString("car_sacado");
                        pesqcontasncobra= rs.getString("car_ncobra");
                        pesqcontastipo= rs.getString("car_tipo");
                        pesqcontasvalor= rs.getString("car_valor");
                        pesqcontasstatus= rs.getString("car_status");
                        pesqcontasdesc= rs.getString("car_desc");
                        pesqcontasobs= rs.getString("car_obs");
        }
              
               
                  
                        i++;  
                                        }
                       if(i==0){ // Verificando se ha dados cadastrados atraves da variavel i

                        JOptionPane.showMessageDialog(null,"Código inválido!\n Digite um código válido!","Resultado",-1);

                    }else{
                       alteracaocontas = true;
                       new GUICadContas().setVisible(true);
                       this.dispose();
                       
                       }

                 

                } catch (Exception ex) { // Consulta mal sucedida
                    JOptionPane.showMessageDialog(null,"Erro ao consultar!","ERRO",0);
                }

            } catch (SQLException ex) {
                // Conexão com servidor mal sucedida
                JOptionPane.showMessageDialog(null,"Erro ao conectar com o servidor","ERRO!",0);
            }

        }catch(NumberFormatException erro){
            // Código fora do formato
            JOptionPane.showMessageDialog(null,"Digite o código corretamante","ERRO",0);
            txtpesquisa.setText("");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            int codigo;
            
                        if (txtpesquisa.getText().equals("") || txtpesquisa.getText() == null){
              
              codigo = (int) tabela.getValueAt(tabela.getSelectedRow(), 0);    
                      
            }else{
                   if(tabela.getRowCount() == 1){
                    codigo = (int) tabela.getValueAt(0,0);
                    
                }else{
                        codigo = Integer.valueOf(txtpesquisa.getText());
            }                 
               }
      
        try{    
            //Declarando a variavel código
           
   
                           
            Conectar.carregarDriver(); // Carregando o driver
            Connection con = null;
        try {
            con = (Connection) DriverManager.getConnection(url2, username, password);
        } catch (SQLException ex) {
            Logger.getLogger(GUIPesquisarContas.class.getName()).log(Level.SEVERE, null, ex);
        }
        String sql ="";
                         String tipo = combotipo.getSelectedItem().toString();
                         
                         
                     
      if (tipo.equals("Pagar")){
        sql = "DELETE FROM contasapagar WHERE cap_cod ="+codigo+";";
          lugar= "contasapagar";
        }
        
       if (tipo.equals("Receber")){
        sql = "DELETE FROM contasareceber WHERE car_cod ="+codigo+";";
         lugar= "contasareceber"; 
       }
        
        try { // Tratamento de Erros para inserção
            
            // Criando varialvel que executara a inserção
            PreparedStatement excluir = (PreparedStatement) con.prepareStatement(sql);
            excluir.execute(); // Executando a inserção
            
            JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso!!!\n","",-1);
            
          refresh(tabela,lugar);
          
         } catch (Exception ex) { // Consulta mal sucedida
            JOptionPane.showMessageDialog(null,"Erro ao consultar!"+ex,"ERRO",0);
        }

        }catch(NumberFormatException erro){
            // Código fora do formato
            JOptionPane.showMessageDialog(null,"Digite o código corretamante","ERRO",0);
            txtpesquisa.setText("");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bttvoltarmenupesquisar9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttvoltarmenupesquisar9ActionPerformed
  this.dispose();       
  new GUIPesquisar().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_bttvoltarmenupesquisar9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPesquisarContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPesquisarContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPesquisarContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPesquisarContas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPesquisarContas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttvoltarmenupesquisar9;
    private javax.swing.JComboBox combotipo;
    private java.util.List<View.Contasapagar> contasapagarList;
    private javax.persistence.Query contasapagarQuery;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtpesquisa;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
